### ISSUE TITLE
DP:101 Eth Pool for POS

### ISSUE THREAD

**Issue by Prawn14** [district0x/district-proposals#101]
A previous idea was suggested to set up a pool for ICO investing and I had a similiar idea for creating an ETH pool for becoming a validator for when ETH changes over from POW to POS. 

It's been rumored that validation will require 1000ETH when it is first implemented. 

Validator rewards would be paid out on a percentage basis per person in the pool dependent on the amount of ETH they have invested. 

The block chain answer could be voted on by those who are invested.

To remain a validator could  be voted on some type of biannual or annual basis. If the pool votes not to be a validator anymore all eth that was initially invested will be returned.

**Comment by aaqilaziz** [comment]
For your proposal to be considered by the team, it has to follow the guidelines and format explained in https://github.com/district0x/district-proposals :)

**Comment by Prawn14** [comment]
Sorry but unfortunately I have a two year work project that will consume much of my time. If someone else would like to officially set up the proposal then go for it. Thank you for your response and good luck with the platform.

**Comment by imdying** [comment]
also you could probably just do this with a smart contract..

**Comment by mckmuze** [comment]
If you would like to elaborate on this proposal we can reopen it for you. I'm going to close it for now.
