### ISSUE TITLE
DP #108 Ad Jam: An Auction district to obtain ad space on districts

### ISSUE THREAD

**Issue by talesfromthecrypto** [district0x/district-proposals#108]
# Name: 
Adjam.io

# Purpose: 
An open auction for ad space on districts. Users can auction against each other to advertise on participating districts.

# Description: 
an auction style district using cryptocurrency to purchase ad space on districts. Ads would be vetted by the district. Districts can decide whether they would like to have ad space auctioned or not. profits would be split among token holders. Districts can advertise on other districts. 

ETH address: 0xbD04159509eb9646b30068da6c6B21aBe3F4e63B

**Comment by Alexand0x** [comment]
Generally, any use case that's expected to offer services directly to other districts on the network functions better as an extension of d0xInfra than an individual district - we call this auxiliary modules.

**Comment by mckmuze** [comment]
Considering this is more of a D0xInfra feature request or module idea I will be closing this for now.
