### ISSUE TITLE
DP#109: Car Parking Sharing District

### ISSUE THREAD

**Issue by criscasta** [district0x/district-proposals#109]
# My Slack Nickname: Omwith

# Name: Car Parking Sharing District

# Purpose:
The objective of this platform would be to help you sharing the costs of a parking slot in big cities with other members. 

# Description:
As someone who owns/rents parking, this district would allow you to put into the market the characteristics of your parking slots (eg. localization, dimensions, etc), and a calendar with days/times that would indicate when your parking slot would be free for other users to use. 
This way, you can benefit from a reduction of your monthly fee, and a new user or users can benefit from your parking slot when no one uses it. 

## Required features:

- Marketplace with profiles for looking for parking slot and for offering parking slot.
- A voting system to show your popularity and reputation, etc.
- Calendar and booking process. 
- The invoicing system to distribute payments within the members accordingly

# Engagement with other districts
This can be linked with the [DP#110: Car Sharing District](https://github.com/district0x/district-proposals/issues/110)

### Creation of value is what keeps a community alive!

If you support this idea, please leave a comment and commit your DNTs! :)

**Comment by imdying** [comment]
could have QR codes spray painted on the park and people could book through
an app.

**Comment by mckmuze** [comment]
Please provide an ETH address if you would.

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
