### ISSUE TITLE
DP#110: Car Sharing District

### ISSUE THREAD

**Issue by criscasta** [district0x/district-proposals#110]
# My Slack Nickname: Omwith

# Name: Car Sharing District - A ridesharing community

# Purpose:
The objective of this platform would be to help you sharing the costs of your car trips with other members by connecting drivers with empty seats to people traveling the same way (similar to BlaBla Car, but decentralized and in own district).

# Description:
As car owner, should you need to do a long journey trip, you may want to invite others who may be traveling the same way to join you. 
The district should allow people to share the costs in DNTs.

# Required features:
- Marketplace with profiles for car driver (offer) and travelers (demand)
- A voting system to show your popularity and reputation, etc.
- Google map or similar to show and describe exact itinerary
- Calendar and booking process.
- The invoicing system to distribute payments within the members accordingly

# Engagement with other districts
This can be linked with the [DP#109: Car Parking Sharing District](https://github.com/district0x/district-proposals/issues/109)

### Creation of value is what keeps a community alive!

If you support this idea, please leave a comment and commit your DNTs! :)

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.Expanded Text
