### ISSUE TITLE
DP #117: Digital Land Contracts

### ISSUE THREAD

**Issue by skzboy1985** [district0x/district-proposals#117]
**Name**

Digital Land Contracts

**Purpose**

Bridging the world’s real estate with safe and decentralized digital assets

**Description**

_Problem:_ Today, the vast majority of real estate transactions take place with the help of typical mortgage loans. Banks and financial institutions stand in the way of both buyers and sellers. However, they tend to charge a high interest rate that is called the *prime rate*, the lowest rate of interest at which money may be borrowed commercially. This is dictated by the discount rate which is set by the Federal Reserve. By having banks, escrows, mortgage brokers, insurance companies and other related financial parties sit in the middle to reduce risk, the cost of the actual real estate has skyrocketed and what a buyer would pay for in a 30-year loan is at least 50% more than the real estate itself.

_Proposal_: Have a way to transact between the seller and the buyer, with no intermediaries. This would function like a land contract, without the cons of risks of the seller whisking away with the money (e.g. seller not paying the lending institution that he/she bought from), contract mistakes, and visibility to where the money actually is.

Address: 0xdd2bF3703195bE8AB6d51CcAD664385e997C30b0
slack name: sidwyn

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
