### ISSUE TITLE
Clothing Marketplace: Cheaper Than the Rest

### ISSUE THREAD

**Issue by loucap1015** [district0x/district-proposals#118]
Name: Clothing Market Place
Purpose: Purpose of the district would be to have users search clothes based on the type they selected, and do it using cryptocurrency with shipping specified by the seller.. these clothes could be new or used, but the intention of the marketplace is to sell clothes cheaper than one would usually be able to find them, thus creating interest in the district. 
Description: The district would be an Ebay-style theme with users searching for clothes based on certain types/styles they wanted. (Broadly, summer, spring, winter, fall clothes) and could eventually become more specific. A user friendly interface would support easy to locate styles of clothing for whatever the buyer needed. A seller would post the listing to the main page of the certain type/style of clothing that was being sold and buyers could easily browse these listing using the style/type of clothes they needed. Searching and filtering could be done by style/type (obviously), price (cheapest to most expensive), date posted, or searched by username of seller. (Accounts would need to be created by both buyer and seller) Overtime, buyers and sellers would accumulate “ratings” to rank their reputation as reliable buyers/sellers, and a scale of satisfaction associated with each buyer/seller would be implemented as well. Payments would be in cryptocurrency (bitcoin, Ethereum, litecoin, zcash) Invoices would be issued correctly after transaction completed. 
0xEb8c10CAec4733054Ab841b7845715E41BC8E469

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
