### ISSUE TITLE
Threads - second hand women's designer clothing

### ISSUE THREAD

**Issue by tonysheng** [district0x/district-proposals#120]
## Threads

Second hand women's designer clothing. 

## Purpose

Buy and sell clothing, shoes, and accessories from fellow fashionistas. 

Designer fashion is one of the biggest verticals for existing marketplaces (e.g. Poshmark, ThreadUp, Tradesy). 

## Description

* Each seller has a closet that contains listings for items they wish to sell
* Listings show title, metadata (like size), description, pictures, and price
* Buyers can buy at the asking price or offer a lower price
* When buyers purchase an item, funds are held in a contract until the item is confirmed delivered at which point they are released to the seller
* After a transaction, buyer and seller give each other a rating--this impacts buyer and seller reputations which are visible throughout the district
* Transactions can be paid in Eth or any Eth token
* Token holders that stake for the district will have a say in decisions that impact the district overall

0x7a364D25c4b0830733d3470DDFFeA3B6979D6944

**Comment by mckmuze** [comment]
I'm going to close most of your submissions that are similar. I would love to see a general purpose market and these could all be categories in that market. If you have a specific market function that would differentiate them from one another please write a thorough explanation about how it would work and all the technical details involved in differentiating that market place and I would be happy to reopen it as a single district proposal.
