### ISSUE TITLE
0xpert - marketplace for expert knowledge

### ISSUE THREAD

**Issue by tonysheng** [district0x/district-proposals#122]
## 0xpert

Marketplace for expert knowledge

## Purpose

Discover experts in valuable fields to guide your project or company.

## Description

Like a decentralized self-serve GLG (https://glg.it/) 

* Each expert has a profile with their credentials, reputation, and billing rate
* Users can search for experts by experience and skills
* Users can book experts for meetings at their rate or message them to negotiate a different rate
* When users book an expert, funds are held in a contract until the end of the meeting. If the user is satisfied, the funds are released to the expert
* Not sure how dispute resolution would work yet
* Token holders that stake for the district will have a say in decisions that impact the district overall

0x7a364D25c4b0830733d3470DDFFeA3B6979D6944

**Comment by mckmuze** [comment]
This is very similar to some of the other proposals labeled with "Similar Market: Educational". Some of the other ones are similar in function and I encourage you to collaborate with them if you see one that interests you.
