### ISSUE TITLE
Minermart - new and used cryptoasset mining equipment

### ISSUE THREAD

**Issue by tonysheng** [district0x/district-proposals#123]
## Minermart

New and used cryptoasset mining equipment

## Purpose

Community driven marketplace for equipment used for mining--both ASIC and GPU.

## Description

* Each seller has a shop that contains listings for items they wish to sell
* Listings show title, metadata (like manufacturer), description, pictures, and price
* Buyers can buy at the asking price or offer a lower price
* When buyers purchase an item, funds are held in a contract until the item is confirmed delivered at which point they are released to the seller
* After a transaction, buyer and seller give each other a rating--this impacts buyer and seller reputations which are visible throughout the district
* Transactions can be paid in Eth or any Eth token
* Token holders that stake for the district will have a say in decisions that impact the district overall

0x7a364D25c4b0830733d3470DDFFeA3B6979D6944

**Comment by mckmuze** [comment]
I closed this for now. If you would like to elaborate on this proposal and continue it's development please include a thorough explanation or mock ups and I can reopen this proposal.
