### ISSUE TITLE
GetDesign - beautiful designs for your project or company

### ISSUE THREAD

**Issue by tonysheng** [district0x/district-proposals#124]
## GetDesign

Beautiful designs for your project or company

## Purpose

Get help with art, logos, and other assets from a community of designers. 

## Description

* Each designer has a profile with skills, a portfolio, and a list of services and prices
* Buyers can buy a service 
* When buyers purchases a service, funds are held in a contract until the service is completed delivered at which point they are released to the seller
* After a transaction, buyer and seller give each other a rating--this impacts buyer and seller reputations which are visible throughout the district
* Transactions can be paid in Eth or any Eth token
* Token holders that stake for the district will have a say in decisions that impact the district overall

0x7a364D25c4b0830733d3470DDFFeA3B6979D6944

**Comment by mckmuze** [comment]
I encourage you to collaborate with other people in the category tag 'Similar Market: Design/creative Arts'
