### ISSUE TITLE
Gift Card Marketplace

### ISSUE THREAD

**Issue by GregFoley** [district0x/district-proposals#13]
## Name:
Spend.eth

## Purpose:
Allow people to spend ether more easily or turn gift cards into ether. 

## Description:
It's a lot easier to consume with bitcoin than ether, and we should catch up. Purse.io is a popular bitcoin use-case, and many more meatspace businesses take bitcoin than ether. I'd like to see it become easier to turn ether into consumption. We could substantially increase the utility of ether with either a Purse.io-style Amazon purchasing service or a simple gift card marketplace. I think this is an obvious use case which someone else will do if we don't. district0x seems perfect for it, and it would likely give us a marketplace generating significant revenue early on. 

"@gregfoley" on Slack

**Comment by rboyd** [comment]
cool idea, I've used http://www.raise.com/ in the past. would you use reputation to mitigate counterparty risk of sellers with bad gift card numbers? eventually if you get the merchant to tokenize their gift cards then you can prove validity, but consider how to handle in the meantime.

**Comment by GregFoley** [comment]
Reputation management like eBay is an obvious solution. To me, the holy grail of Ethereum is distributed reputation management, and I sometimes toy with the idea of being the person to try and pull it off myself. 

An escrow system like Purse.io uses is another option. There, they release your payment when you receive the goods that were purchased on Amazon for you. 

I hadn't seen raise before. Do you know how they handle it?

**Comment by AngeloAdam** [comment]
please send me a direct message on district0x slack to discuss your proposal @angelo Thanks

**Comment by GregFoley** [comment]
@gregfoley on Slack.

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.Expanded Text
