### ISSUE TITLE
Book0Biz - Decentralizing & Upending CRM - Customer Relationship Management

### ISSUE THREAD

**Issue by VulnerableToEMP** [district0x/district-proposals#131]
Almost every major organization pays a centralized profit center to help manage their relationships.  It is time this data gets decentralized.  Adding this crucial business tool to the District0x ecosystem will help drive users to our ecosystem, increasing the usage of other districts and in turn increasing the value of DNT.

**Comment by mckmuze** [comment]
This issue will be closed. If you want to adhere to the proposal standards  outlined in the repo I can reopen this for you after you elaborate on this.
