### ISSUE TITLE
DP #134 Scholar District

### ISSUE THREAD

**Issue by arcoso** [district0x/district-proposals#134]
Name : Scholar District
Purpose : College Reviews
Details : A district for colleges and students to organize various schedules, plus uncensored reviews of a myriad of topics.  Topics ranging from pricing, professor reviews, dorm life, quality of teaching ability.

**Comment by mckmuze** [comment]
Thanks for this submission, we will be happy to reopen once more details have been included for the community to discuss or we see traction around this proposal.
