### ISSUE TITLE
Nomadia is a district for all digital nomads old and new. 1 place to find work, find accommodation and to socialize.

### ISSUE THREAD

**Issue by Elrohir84** [district0x/district-proposals#136]
Nomadia the district for digital nomads. Share travel experiences, find work, talk about the Crypto world and more.

Nomadia would be a go to district for everyone who like to be independent/decentralized. Nomdia could work together with ETHLance to provide work, a source of information for traders about the newest ICO's and Tokens, A travel advisor to create a vast knowledge base where the internet and life is good to work from. And a place to socialize and meet new people. Nomadia would be the district that no Digital Nomad could do without.

0x45540ffEB8ffF1c6D14b0E9a431B826381b8679D

**Comment by mckmuze** [comment]
Thanks for this submission, we will be happy to reopen once more details have been included for the community to discuss or we see traction around this proposal.
