### ISSUE TITLE
districtb0t

### ISSUE THREAD

**Issue by jonfix** [district0x/district-proposals#137]
## Purpose

Today there is more people than yesterday looking for invest on cryptocoins.
More people than yesterday wanting to invest in an startup, or start its own.
More people who is working to open it´s business to the wide world.
More people than tomorrow, and less than yesterday.
But we want even more people, because the more we are, 
the stronger wil be our descentralized world.
There is a will, but there is also a brake:
everytime someone wants to support an initiative like **district0x**, has the same problem.
Where can I buy ethers? How can I send them to my wallet? How can I support this initiative?.

We always ask a friend, but everybody doesn´t have one. 
So we will create that guide figure.

Let´s help people joining us, by creating **districtb0t**, the IA chatbot who helps any user to understand **district0x**, join invest and work on the platform.
 
## Description

**Districtb0t** will be a user focused bot, whose interactions will always be with an only purpose: helping people to join us. 

We won´t create a super monster chatbot talks about everything; instead of it we will develop a simple one, working the most important doubts and building a virtual guide to help the new users.

For that, we will do it with “open bot”, where every user of **district0x** can make it´s own topic proposals, and work in them. The idea is to ask to other users what doubts they had in their process, and start training the bot to help the new users so they can be part of us easier.

### The topics

The topics will be choosed by the users: they will vote for the main topics, and also propose new ones. **Districtb0t** will be able to talk about this topics, but also to learn the needs of the new users and include more topics. Examples of topics.

- What is **district0X**?
- How it works?
- Who is behind of it?
- Legal questions?
- And the taxes?
- How can I create a district and make it strong?
- How can I start?
- How can I invest?
- How to secure your currency?
- How to buy and sell Ethereums and DNT?
- How to implement **district0x** to your case: integrate plugins or modules?
- How to contribute in **district0x**; buying DNT, voting, proposing new **district0x**?
- How to know the margin and value of your DNT and Ethereum?

_Please, help us creating more topics_

## Second phase

Any chatbot needs to be the greatest bot it could be before thinking about adding more functionalities. But working on it doesn´t mean to forget how to make it bigger, stronger, and more useful.

That´s why once we finish building the first beta of our bot, and after adding users topics, we will start working to add more functionalities so we can even add more value to **district0x**. 

Here are some of those utilities we would love to work once the bot is helping the users to use our platform:

### Payments and DNT wallets
As we said, **districtb0t** it´s user-centric chatbot, so we will integrate the token payment or exchange utility in the chatbot, so the user would do it in the conversation, instead of following all the steps. It´s easy, it improves the user experience and it makes easier to bring and move money in **district0x**.

### Suggested questions
Sometimes the user doesn´t know how to ask something to the bot, so we will show some suggested questions to the users, so they only have to click them to see the answer.

Also, we can update this questions, including different hot topics of the week. For example, if some users are talking about “Scam” in Slack, one of the suggested questions will talk about it.

### Sustainability
In every new product and platform, we need to be efficient and not to spend money and resources in utilities that people is not going to use. That´s why **districtb0t** sustainability will be attached to it´s own succeed. The more people who will use it, the more resources and tokens we will need to update the bot and keep it working. 

### Languages
Once we develop the bot in english, we can can offer the interface in more languages like spanish or french, and keep working on it with the users to see if there is a need to add more languages. Because if there it is, there will also be a will.

### Launch, test, learn.
We have many different ideas to make this big, but our efforts are focused to make it work first. That´s why we are going to work for short wins, so we can build the big one. The idea is simple:
To launch, to test, to learn. And start over. To launch to test, to learn. To start over again. Launch, then test, then learn. And over and over again. 

0x0027F9b95175C23ce6622FEAA37e2FD52c123257

**Comment by sebasbelou** [comment]
The question is not very quick but to arrive

**Comment by sebasbelou** [comment]
Excuse my evil English. In the previous message I meant that “Together we will go more slowly but we will go further”.

**Comment by Alexand0x** [comment]
I like the idea of an FAQ bot with some amount of self-learning capabilities that we can deploy to our various chat rooms and social media. However, I don't think this really qualifies as a district proposal, as it's neither a marketplace nor a community.

**Comment by basiccrypto** [comment]
I think this would be interesting if there was some sort of bounty system placed around this but agree with @Alexand0x that it seems like it would be tough to develop an actual district unless it morphs into something like a consultancy district like #27

**Comment by jonfix** [comment]
Thanks for your contributions.

As @Alexand0x says districtb0t could be the channel through which users can connect to group chat. The query to check who is connected in order to chat privately is offered by Slack.
In any case, districtb0t can provide facilities district0x citizens if we stablish an alliance with cofund.it, rocket.chat, whatever the solution or the one provided by MicahZoltu:
“Perhaps instead of not using Slack, consider changing the way you do invites so people can't as easily sign-up with bots? Or at least, force the bot authors to build custom bots for targeting Aragon sign-ups (right now since everyone uses the same Heroku app for invites the scammers just need to target that one app).” 
https://github.com/aragon/governance/issues/7
In district0x it is expected that many chats or private conversations will be opened concurrently. So the chat message solution should be totally integrated.

--

@basiccrypto @ Alexand0x I am going along with you when you say that districtb0t is not a district0x itself, but it is practical, key and useful tool.
We presented a basic districtb0t, but we thought about a premium service by advisors, similar as [Bridge - P2P Blockchain Consultancy](https://github.com/district0x/district-proposals/issues/27), that gives solutions instantanely or asinchronously to who district0x-related requests. 
A network of “consultant operators” who act like advisor is the best support possible.
In the future the online premium support that provides a momentary and direct treatment will lead a service that is up to a complex web experience.
Enabling real-time counselors in chat requires a large group of online advisors, which means a huge effort and cost. A bounty system would a solution.

--

@sebasbelou You know that the cryptocoins and the new digital financial environment generate us situations of uncertainty in the network. On many occasions we are helpless without knowing where to look to solve our problem with the ethereum and its management.
The adoption of district0x should be simple and easy. With this proposal we help in a good user experience, that will cause other users to try and encourage this dapp; district0x.

**Comment by mckmuze** [comment]
I will be closing this out because this is not really a community or market but I have to say I love the idea. This may be more appropriate as a bot built into Status. You should look into getting this developed.
