### ISSUE TITLE
DP14 - TrustCoin - A crowdsourced address verification to filter out spammers

### ISSUE THREAD

**Issue by adamoo1** [district0x/district-proposals#14]
# Purpose
 
To let the developers behind ICO's let users know which Ethereum addresses and webpages are legitimate through the distribution of a 'Trustcoin' which is kept on a ethereum wallet address This non-transferrable coin has no monetary value but would act as a symbol of validation, letting users know that this address is a valid ICO address. 
 
 
 
# Description
 
To help the crypto community know what is a scam and what isn't. We want to create a symbol of validation for ICOs, it would act like the twitter verification checkmark but for eth addresses. 
 
We would create a zero monetary value ERC20 token named 'Trustcoin'. Address owners can verify that a certain ethereum address is connected to these email accounts, slack address, slack users, ethereum wallet addresses, website address and contracts by signing them to the blockchain using something like Keybase or Parity's email verification service. 
 
They are then given a 'Trustcoin' for storing on their ethereum address once they are validated. The 'Trustcoin' is not able to be transferred. When a user on MyEtherWallet or MetaMastk tries to send to the ICO address, a validation check is presented asking them to confirm it is the correct address by displaying the various other accounts it is tied to. 
 
**MyEtherWallet and Metamask integration**, MyEtherWallet checks the ethereum address to see if it contains a 'Trustcoin', and if it does not they would warn the user which the user can decide to proceed or not.
 
**Slack Bot**, ethereum addresses posted in channels are compared to known trusted addresses that the ICO submitter validates and a warning message produced by Trustcoinbot would warn users that this is not the ICO address. 
 
How does one earn a Trustcoin? Here's where District0x comes into play. Create a 'Trustcoin' district, the people in this district act as validators who look at the information provided by the ICO submitter and confirm it is correct by visiting the website of the ICO and also confirm the other pieces of information manually. They vote yes that the information is valid. Each validator will be given a reputation score based on past validations and an equal percentage of proceeds earned through the district.
 
**How can we trust the validators?** They follow the same steps followed by the ICO Submitters but for their own reddit account, name, email address but instead of having that information publically viewable, they use zero knowledge proofs to cryptographically sign that information to the blockchain. This way we have can confirm its existence without viewing its contents. This way validators are putting their name on the line to verify the address is correct. 
 
The 'Trustcoin' district will have an ethereum address with a multi sig, requiring 65% of the district inhabitants to vote if any changes are needed to the district. This address will also work as a donation address and will be presented in various places for when we help users avoid scams. These funds will be distributed among the validators after each successful ICO. ICO's can also donate to this address which will bump them to the top of the validators queue.
 
If the validators validate the wrong information then they are unable to validate another ICO Submission for X amount of days and forfeit  the TrustBounty.
 
**How does one become a validator?** It will work on the buddy system, we get certain people within the crypto community to become the first validators, they then vouch for their buddy, that buddy is now able to vouch for others and so on. The penalty for validating incorrect information is steep though and will trickle back through the buddy system affecting the vouchers. 
 

 
 
# How this works from the ICO Submitters perspective
 
John Smith is the CEO of a up and coming ICO and he wants to ensure that users won't be scammed. He cryptographically ties his website URL, Ethereum wallet address, twitter, email address and slack address together confirming that this person controls all of these using something like keybase
 
He submits this hash to the TrustCoin District for verification which becomes a TrustBounty.  The ICO Submitter has the option to donate Eth, or any ERC20 token to the TrustCoin District wallet, if they chose to do so, Validators would want to validate this TrustBounty first. After verification is confirmed, the TrustBounty is satisfied and a Trustcoin will be minted and sent to the Ethereum wallet address provided. This will act like a Twitter verified checkmark, it will let user know that this ethereum address is tied to an ICO.
 
 
 
# How this works from the validators perspective
 
Validators are only as good as their word, and because we aren't staking funds, we want to stake our online identities. Using Zero Knowledge Proofs, validators can submit their reddit, facebook, and email account to the blockchain. This will create a hash which we can use as proof of existence, we are able to see that is there and confirm it is legitimate but not read its contents . Validators review the ICO Submissions, confirming each piece of data submitted by the ICO Submitter is valid. Once they confirm it is accurate, they can vote the submission as valid. Once an ICO Submission has x% amount of valid votes within the TrustCoin District then a Trustcoin is minted and sent to the ICO Submitters wallet address. Validators will share an equal % of the TrustBounty (if the ICO Submitter donated) and will share an equal % of donations to the  TrustCoin District wallet address.
 
 
 
**Questions:** 
 
•	Can MEW and MetaMask query ethereum addresses for the presence of a certain token?
•	How do you stop someone from creating multiple accounts, thus creating multiple validators? 
•	Can Zero Knowledge proofs work that way, when they will they be available in Ethereum?
•	Can Trustcoinbot read messages in slack channels or would it have to be an IRC bot connected to slack?
 
 
Thank you for taking the time to read this idea! I'm very open to any suggestions and comments
 
Cheers
 
Slack Username = Adam

**Comment by mckmuze** [comment]
This is an interesting idea. However I'm struggling to see how this would work as a market. I will be closing this out. I will reopen if you can elaborate on how it would work as a marketplace. This appears to be more of an idea to launch an ERC20 token more than a district.
