### ISSUE TITLE
DP #141 Real Estate Market Districts

### ISSUE THREAD

**Issue by alphathree** [district0x/district-proposals#141]
**Name**: Real Districts

**Purpose**: Allow publishing of rentals and sales of property. This industry is known for fees and costs to connect sellers with buyers or renters. Avoiding lots of commissions on agents. People can publish their property in the district. There could be more local districts, or more global districts. The connection between the buyer and the seller is what costs a fee on the system.  

**Description**: Real Estate rentals and purchases is a huge market. With many platforms charging absurd fees for listing a property. People that rent usually has to go through an agent (big fee), and renters or sellers usually have to pay high fees for publications.

There are several monetization models that could work. Which would make the connection between tenants, owners, renters, much more efficient and without middle men. With instant and cheap payments to maintain the network.

Ratings play an important role in some scenarios, like renters leaving rating on tenants and vice versa. Buyers leaving sellers feedback for a purchase or just an engagement. 

All parties would avoid all sorts of fees, while keeping the districts transparent.

This system would compete with Zillow, Trulia, and all other global real estate platforms.

**Comment by wan0054** [comment]
Great idea, but i think having a district like this in the early ages of District0x, it is not going to be a very active and difficult to find legitimate matches. Give it 3 or so years then this idea will be perfect

**Comment by alphathree** [comment]
could be. I think it goes in line with ethlancer in some aspects. IMO worth
building based in industry need+size.

**Comment by mckmuze** [comment]
Can I get a token address please.

**Comment by alphathree** [comment]
0x02D51A3a2F8d554079636d55d2e925ef7716aEeE

**Comment by Bradymck** [comment]
@alphathree got it

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
