### ISSUE TITLE
Tokenize.it

### ISSUE THREAD

**Issue by koreansovereignwealthfund** [district0x/district-proposals#147]
>Marketplace for high valued items
>Tokenize the following
>Cars
>Houses
>Antiques
>10k EUR+ valuation items
>Mesh smart contract with legal contract, "as is", sale after personal review, etc
>Sync extension to access blockchain dapps and contracts
>Put it on market
>Sell for cheap, instantaneously transact asset

Probably a legal hell but would be really neat to just sell a car on the blockchain and circumvent legal fees, transaction times.

**Comment by mckmuze** [comment]
Please keep in mind, to qualify as a proposal it needs to adhere to the proposal standards outlined on the root page of the proposals: https://github.com/district0x/district-proposals

I'm going to be closing this out but if you want to elaborate on this and structure it in accordance with the proposal standards I can reopen it.
