### ISSUE TITLE
 DP#151 - FruityCake: Vegan/raw food distribution for schools and hospitals

### ISSUE THREAD

**Issue by niex2** [district0x/district-proposals#151]
# **Name:**
FruityCake: Vegan/raw food distribution for schools and hospitals

# **Purpose:** 
The aim of the project would be to make a food-distribution system that serves vegan / raw foods for schools and hospitals, and it's governed by the community and sustained by the community.

# **Description:** 
There would be a map where you could see how can you help with the making of vegan/raw food supply for the nearby schools/hospitals, and then there could be the possibility to raise money for the making of it, with donations or investments.
The map would show that there are the schools and it would show the current progress of achieving vegan/raw food supply, and you could sign up as paid or volunteer worker, you could send money or offer anything necessary to achieve the vegan/raw food supply of that place.
There would be different roles to fill, for example  work in the kitchen, transport, legislative work for example lawyers, etc. The map would show the current composition of the team for each area, which roles are filled, which instruments we have, how much supply is needed and things like that, so it would be easy to join the parts together. Some roles would be more local, some roles would be less local and would cover more areas. For example, the people who work in the kitchen would form a smaller circle, the legislative roles would cover a bigger circle, because for that you don't need to travel every day to the specific area. The transportation would be again a different role with different scope.
For each role, there would be a default scope, but the scope could be adjusted according to the needs of the people who are filling the roles, so, for example, if a lawyer or somebody who is working in the transportation of the products, says he can cover this 150 km radius zone, than it's possible to do so even thought the default is for example 10 km radius for that role. Or he can specify which exact factories he or she can fill the role, with the use of the map.
The system of the district should be able to facilitate the payment of the workers in fiat (accounting, etc), and should incentivize the volunteer workers and the paid workers as well with some specific token that later might have value.

0xCc5bf0C766aae63c653480b12b232927c1Fd4619

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
