### ISSUE TITLE
DP#153  ShipIt.District0x - The New Global Shipping Platform

### ISSUE THREAD

**Issue by Royan-17** [district0x/district-proposals#153]
[ShipIt.District0X.v1.1.pdf](https://github.com/district0x/district-proposals/files/1277238/ShipIt.District0X.v1.1.pdf)
[ShipItDistrict0x.pdf](https://github.com/district0x/district-proposals/files/1277243/ShipItDistrict0x.pdf)

Name:     ShipIt.District0x

Because “disintermediating human trade –business- is the first step towards a fairer and more efficient world” - Luis Cuende / Aragon_

Purpose:
To Create the largest decentralized autonomous open market bringing together the community of the commodity trading industry (cargo owners, exporters, importers) with the community of the transport industry (shipping lines, airlines, trucking companies, logistic companies, freight forwarders and clearing agents). 

Objective: 
To remove intermediaries and frictions in the logistic chain, reduce the cost of shipping while increasing asset utilization for the carriers, improve end-to-end cargo tracking, remove century old paper trails, and improve cargo clearance process (paperless export/import clearing processes).
ShipIt.District0x is an opened platform using other existing successful blockchain solutions to offer the most compelling value proposition, such as Civic for Identification Verification, Chainy of Everex for poof of existence of original documents, Aragon for governance and arbitration, Agrello for legalization of digital documents and processes and for litigations, Everex cryptocash for most efficient and cheapest international transfers…

Description: 
ShiptIt.District0x is the largest decentralized autonomous shipping marketplace allowing:
1.	Posting and listing, searching and filtering of all shipping lines ocean schedules, booking of open space at discounted rates (back-haul trades), space slot auction…
-> customers gain access to the most extensive selection of ocean carriers in one platform, saving valuable time through powerful search capabilities by port of load, port of delivery, voyage number and vessel name AND transit times, freight rates, frequency.
-> the ocean schedule database will be automatically and constantly updated through EDI link to the shipping lines which will join the ShiptIt.District0x community
-> the carriers will have the ability to offer a freight rate (as per today), as well as discounted rates on back-haul trades subject to open space, and –NEW & UNIQUE feature of ShiptIt.District0x - offer limited space on auction.

2.	Freight booking: customers will be able to book their cargo direct via ShiptIt.Booking at a click of the mouse (existing platforms can be integrated into ShiptIt.District0x, updating shipping lines’ booking system automatically).

3.	Shipping Instructions: digital templates with auto-fill fields will allow to move from the booking step to the shipping instructions step seamlessly. 
-> these shipping instructions will be automatically transmitted to the shipping line via EDI
-> Identification verification of the parties (shipper, consignee, notify party) may be potentially provided by integrating Civic Technologies into the ETH/District0x stack.
-> Packing list will be provided to shipping line in an electronic format, which Chainy (see further down) will secure and track.
-> agriculture, phytosanitary and other cargo certificates will be sent with the shipping instructions, which Chainy (see further down) will secure and track.
4.	Freight payment: ShiptIt.Payment module will allow the freight payer to proceed with freight payment electronically (conventional fiat or cryptocurrency). Naturally, cryptocurrency payment will allow cheaper/more efficient international transactions (Everex cryptocash etc can be considered)

5.	Creation of the Ocean Bill of Lading: NEW & UNIQUE feature from ShiptIt.District0x
-> the shipping line will be able to issue the Ocean Bill of Lading as a conventional document (same as today) or – a revolution - as a digital document.
-> Using Chainy (Everex product), the century old Ocean Bill of Lading will be “cryptolized” and its dual role will now eventually be split:
a.	Transportation contract between the shipper (or his/her representative) and the shipping line will be issued (smart contract using similar template as the current OBL
b.	Document of Title between the shipper and the consignee, with the option of escrow account guaranteeing payment of the cargo against delivery of the cargo via smart contract. The option of joint cargo survey before payment is another option that ShiptIt.District0x will provide in the most efficient and economical way as cargo surveyors will be members of the community.
Chainy will allow to provide:
	- Proof of Existence of the Original OBL Document
	- Single ownership of the Original OBL Document at any point in time
	- Permanent access to Copies of the OBL Document
	-Transfer and tracking of the Original OBL Document
6.	Cargo Clearance: NEW & UNIQUE feature of ShiptIt.District0x
Cargo shipped through ShiptIt.District0x will benefit from faster and more efficient cargo clearance process.
Such process usually requires about 10 to 20 different papers.
Considering all documents will have been digitalized, secured and transferred to the relevant authorities ahead of the vessel arrival at destination, the Customs and other cargo inspection authorities will be able to conduct their so called Pre-Arrival Cargo Clearance in a systemic and systematic manner, and the cargo will be available within 12 to 24 hours after discharge instead of 3 to 7 days in most ports of the worlds.

7.	Cargo Insurance: insurance companies will join ShiptIt.District0x community and offer appropriate insurance policies 

8.	Cargo claims and Commercial conflict resolution: 
To save time and money to the parties, ShipIt will use Aragon as arbitration court. 
The parties will then be able to refer the case to court if they wish.

Business pool:
- Volume pool: 
+/- 35 million containers shipped every year, 
7 to 10 million Bill of ladings = 7 to 10 million sea freight transport contract + 7 to 10 million cargo sale agreement
Each shipment (bill of lading) will require the involvement of another minimum 2 to 4 logistic service providers (trucking, clearing, forwarding, warehousing etc) at both ends, meaning 14 to 40 million extra transactions minimum or a total volume pool of 28 to over 60 million transactions.
- Value Pool:
a. Value of cargo shipped annually: in excess of 4 trillion USD,
b. Estimated annual value of the sea freight alone is 200 billion USD,
Estimated total logistic cost including trucking, clearing etc should be closer to 500 billion USD.

The above description of ShipIt for the maritime industry can be developed in the same way for the air transport industry, the road transport industry, cargo consolidation (groupage and LCL) industry…

**Comment by mckmuze** [comment]
Can I get a token address for this proposal please.

**Comment by Royan-17** [comment]
Hi There,
Is that an ERC20 compatible wallet address that you need? Like ImToken?
Krgds
Vincent

Sent from my iPhone

On 8 Sep 2017, at 02:13, Bradym <notifications@github.com<mailto:notifications@github.com>> wrote:


Can I get a token address for this proposal please.

**Comment by Bradymck** [comment]
@Royan-17 Yes, an ERC20 token address that you control if you would.

**Comment by Royan-17** [comment]
0x28C2897122286A35738413E264942a781AF5c06A

Krgds


Sent from my iPhone

On 12 Sep 2017, at 04:17, Bradym <notifications@github.com<mailto:notifications@github.com>> wrote:


@Royan-17<https://github.com/royan-17> Yes, an ERC20 token address that you control if you would.

**Comment by happyrobotstudio** [comment]
very nice, the idea looks well thought out and addresses a large market with shipping and freight,

the proof of delivery, and case arbitration framework looks great, if the  framework is proven for the case of shipping, could scale to amazon level door to door shipping perhaps also =)

very cool district proposal

**Comment by Royan-17** [comment]
Thank you for your feedback.
You are absolutely right. Amazon and/or Alibaba could ultimately use the platform (ShipIt / Truckit / Airfreightit and why not DroneIt sometimes in the future). They would appear as the shipper and their customers as consignees. « Simple ».
Seriously large application (and I am from the industry ;-) ).
Issue is voting system of District0x which is really not simple and easy + far too long list of district proposals with too many not delivering substantial benefit from the use of the Blockchain technology. Most of the proposals do not need Blockchain. Could be done on simple web based or mobile app.

Thanks for your support and let’s keep pushing for a large proposal with massive network effect and which could potentially disrupt a very old industry.

Cheers
Vincent

Sent from my iPhone

On 29 Sep 2017, at 12:36, happyrobotstudio <notifications@github.com<mailto:notifications@github.com>> wrote:


very nice, the idea looks well thought out and addresses a large market with shipping and freight,

the proof of delivery, and case arbitration framework looks great, if the framework is proven for the case of shipping, could scale to amazon level door to door shipping perhaps also =)

very cool district proposal

**Comment by happyrobotstudio** [comment]
Indeed, the shipping and verification procedures naturally suit blockchain, 

Yep! I like this idea and have voted

**Comment by Royan-17** [comment]
Thks a lot! Krgds

Sent from my iPhone

On 29 Sep 2017, at 13:09, happyrobotstudio <notifications@github.com<mailto:notifications@github.com>> wrote:


Indeed, the shipping and verification procedures naturally suit blockchain,

Yep! I like this idea and have voted

**Comment by cryptokamikaze** [comment]
I am in the import compliance field and I think this is a great idea and have voted for the district.  My only concern is that CBP is very slow to adapt to new technology and there are many issues that require personal interactions with CBP.

**Comment by Royan-17** [comment]
Thanks for your support!
I am from the maritime industry and I have contributed to setting up a CCP unit in the country where I currently work (not USA). Am in close contact with UNODC.
The platform should actually be able to provide a lot more info, a lot more detailed and a lot earlier than what we have today and we must think about about info should be provided to Customs and Security Agencies si that they can do their work without affecting the privacy of the stakeholders nor the effectiveness of the trade and transport system.
That is where Civic solution (or similar solution) could help.

Good to know you are from import compliance field and for sure your own expertise will be of great value to the project.

Thank you again for your support. 😘🙏


Sent from my iPhone

On 4 Oct 2017, at 05:08, cryptokamikaze <notifications@github.com<mailto:notifications@github.com>> wrote:


I am in the import compliance field and I think this is a great idea and have voted for the district. My only concern is that CBP is very slow to adapt to new technology and there are many issues that require personal interactions with CBP.

**Comment by Royan-17** [comment]
I meant 😉🙏

**Comment by Bradymck** [comment]
Closing as requested by creator.
