### ISSUE TITLE
OnBuy marktplace / Decentralized ,,ebay"

### ISSUE THREAD

**Issue by swissfound** [district0x/district-proposals#164]
**Name** On(line)Buy - a P2P marktplace like ebay, just decentraliced.

Why show our credit card information into the worldwideweb? We have the chance now, to change the way we buy stuff online in marktplaces like ebay!

1.What is OnBuy
2.Why OnBuy
3.Rules
4.Sell & buy

i glad to know the team will be developed the first voted district while iam am fully tech noob but will bring me idee in.

1.What is Onbuy
Onbuy is a peer2peer marktplace like Ebay for selling all your stuff online or buy some new stuff.
For more anonym we can do a filter that the personall infos just show between the buyer and seller.

2.Why Onbuy
OnBuy will be decentraliced, no credit card needed, you dont want to to show google or big companie your informations? Me too!
-No thirrd party, you want buy something? Do it in a few minutes to a hour and the owner can send you the paket one day later, no 5day ti wait for the transaction via your bank.

3.Rules
Yes we all hates rules and regulation, but please calm down. We had to block the gun, drug, childabuse market outside if this district with filters and more. We want no Silkroad. Just to be sure that Law rules and regulations dont destroy this district.

4.Sell & Buy
I personally think in this district it makes sense that we can pay with all erc20 tokens, and bitcoin or we can do a filter what for a currency we want to receive.
-transaction fee. The transaction fee should be 0.08 percent of the amount we spend to buy.
Problems.

I dont think it will be fully anonymus, the reason is we had to show our name and post adress.

**Comment by mckmuze** [comment]
If you would please rewrite this in the district proposal standard in the format I can reopen: https://github.com/district0x/district-proposals


Also, please include an ETH address.

**Comment by Bradymck** [comment]
I will reopen this for now but please include more details to differentiate it from the other markets in the general purpose market category. You can click the tag and see the others. I will be closing out proposals that have no traction or engagement from the creator.

**Comment by Bradymck** [comment]
As you requested I closed your proposal. If you would like to elaborate on this or add to it we can reopen. It's up to you.
