### ISSUE TITLE
Continuously improvement platform for companies with reward system

### ISSUE THREAD

**Issue by Donjacob2099** [district0x/district-proposals#165]
To let companies work more efficiently. It's of utmost importance that the employees at all ranks help thinking for new ideas and also implement them selves. To stimulate to improve it's best to reward for good ideas and good implementation. At the beginning of a new term all reward tokens ($DNT) will be distributed to the employees to have the possibility to reward certain ideas that they like or is best implemented.

**Comment by mckmuze** [comment]
I'm going to close this out for now. Do keep in mind, to qualify as a proposal you need to ensure your proposal adheres to the district proposal standards outlined on the following link: https://github.com/district0x/district-proposals

I can reopen this if you decide to add more details.
