### ISSUE TITLE
EtherStay District Peer to Peer rent/board/house sit pay direct to district member via ERC20 token

### ISSUE THREAD

**Issue by squigita** [district0x/district-proposals#166]
A new District called EtherStay, where members of the District can offer their room, house, house sit for rent/board and receive payment via cryptocurrency with other district members. Members would be able to peruse listings or list their own. Listings would have member ratings and members will also be able to rate listings they have stayed at. Air B n B is a good example except within District 0x there would be no need for a third party overseeing and taking a commission, nor would the need for credit card payment systems, this would be a pure peer to peer offer and payment system. Only EtherStay District members will be able to participate

**Comment by mckmuze** [comment]
I'm closing this for now. We can reopen this after it's revised to adhere to the district proposal standards: https://github.com/district0x/district-proposals
