### ISSUE TITLE
China Foregin Exchange Decentralised 

### ISSUE THREAD

**Issue by honjo294** [district0x/district-proposals#170]
**Name:** District - Direct RMB/CNY/RENMINBI/YUAN 

**Purpose:** Allow a market place where buyers of RMB (for example tourists and offshore business persons) can meet sellers. Chinese banks have strict regulations on capital outflows and try to restrict its citizens from being able to convert into foreign exchange. Some Chinese investors have a need for purchasing foreign exchange reserves which are above the USD$50,000 they are allowed per year by the banks. Create a market place where RMB can be exchanged for other currencies.

**Description** A P2P marketplace in both English and Chinese for domestic Chinese investors to be able to match up buyers with sellers of RMB. This would mean Chinese investors would not need to go through financial institutions to be able to get RMB exchanged.

**Comment by Bradymck** [comment]
Please see the 'Similar Market' Tag for proposals that are similar to your, I encourage you to collaborate with them.
