### ISSUE TITLE
Daigou/Purcashing Agent Market Place

### ISSUE THREAD

**Issue by honjo294** [district0x/district-proposals#172]
Name: District Luxury Purchase

Purpose: To match overseas buyers with people able to purchase goods at prices unavailable in their home market. Currently, Daigou agents charge Chinese customers to purchase goods overseas for them and ship them to them. A P2P market place where people can request goods and people respond with in what the best local price is for that good and the cost of shipping plus what their fee is would cut into this market. Some countries have Luxury goods taxes but when an offshore person sends something to someone this may mean that it is exempt from those taxes, 

Description: The district should have an automatic language translator and allow a P2P exchange of goods, with people posting descriptions or photos of what good they want and requesting people willing to purchase it from their local market to see what the best price is for them. After more trades, they get higher feedback. The purchaser can choose to accept or decline any of the proposed rates. This would allow purchasing agents to compete for business and the buyer from offshore to receive the best deal.

**Comment by Bradymck** [comment]
The deadline to add a token address is today. We do need it before tomorrows distribution.

**Comment by honjo294** [comment]
0xf5b03d014ba330dac228a17b28d26088103e9c70

Eth address
