### ISSUE TITLE
District Language Tutor

### ISSUE THREAD

**Issue by honjo294** [district0x/district-proposals#173]
Name: District Language Tutor

Purpose: To allow language tutors to be able to advertise skype language classes and tutoring. Currently, online websites charge to have tutors, a P2P network would by pass this and allow people to advertise their services for a fixed price per hour etc.

Description: Have a district where people can advertise language lessons directly. So that people increased can browse who is online and what their current price per hour is along with their fluency and rating by past students. The tutor can advertise their hourly rate.

**Comment by imdying** [comment]
great idea. I'd be up for that. Perhaps include some sort of online course
where there is a gamification element. Levelling up etc. Then you can move
on to a higher rated teacher or something.

**Comment by Bradymck** [comment]
This is similar to #135 - https://github.com/district0x/district-proposals/issues/135. 135 is more of an app idea than a market but if you two collaborated this may make a great opportunity to merge ideas.

**Comment by Bradymck** [comment]
The deadline to add a token address is today. We do need it before tomorrows distribution.

**Comment by honjo294** [comment]
0xf5b03d014ba330dac228a17b28d26088103e9c70

Eth address
