### ISSUE TITLE
District Digital Currency - DDC

### ISSUE THREAD

**Issue by WesleyKadou** [district0x/district-proposals#182]
Name: District Digital Currency

District digital currency is a form of digital currency, created and held electronically, No one controls it. District Digital Currency (DDC) is not printed, like dollars or euros etc. 

Purpose: We will use DDC to make instant, private payments online or in-store using a secure open-source platform. Potentially used across all business's built off the District0x platform.

District Digital Currency wallet is a secure digital wallet used to store, send, and receive digital currency like Ethereum.

*Proposal draft coming soon*

**Comment by Bradymck** [comment]
If you want to elaborate on this I can reopen, I'm closing this for now as this sounds more like a general description for an ERC20 token. To be considered a proposal, it would need to be a marketplace or a community. 

Also, do keep in mind that we will be utilizing the 0x protocol to accept any ERC20 token, so a new token is not necessary.
