### ISSUE TITLE
District Bittrix 

### ISSUE THREAD

**Issue by honjo294** [district0x/district-proposals#185]
Name: District Bittrix 

Purpose: A district where people can talk and speculate about why DNT is not listed on Bittrix yet.

Description: Lots of investors have put thousands of dollars into DNT and would have liked some returns but for some reason, there is talk that DNT didn't pay the $5000 dollars to list with Bittrix. This lack of access to major markets has severely dented the number of investors who have access to the project and has seen DNT's market cap fall from $125 million to around $20 odd million. A lot of people would like to find out why it hasn't been listed yet. This community is for investors who have lost significant sums by placing their faith in this project and want to share information on the reasons for the significant decline in market value.

**Comment by Charlie-Mack** [comment]
I think you're confusing investing with speculating. If you invested in District0x, you provided them with capital at their ICO so they could realise District0x with the capital required for development. If you invested in District0x you would currently be sitting at 200% gains. When you purchased DNT on an exchange after the ICO, the only thing you are investing in is the person you bought it off. The only reason you bought into District0x was that you were speculating on its future price hoping that holding the token for a couple of weeks will make you rich. 
Before you "Invest" in a project again, spend time learning about the project and the development team. If you had done your due diligance, you would have realised that this team is not focused on getting the token listed on exchanges to hype the price. They are interested in delivering the product and focusing on development. 
In any case. This is not the place for you to vent your frustrations on your own poor life decisions. Making a mockery of a district proposal in a vein attempt to swiften the process in getting the token listed is about the most childish and immature thing you could do. I mean, seriously, what is your end game here? You think the team is going to look at this at say "Oh no, honjo294 hasn't had 5000% returns buying in at the ATH. Lets drop everything and spend all the runway we have on marketing to hype the token up again."
If you want to cry about the price, then go to reddit.com/r/dnttrader or something.

**Comment by honjo294** [comment]
What are you talking about investing is not about just buying initial
public offerings. Si you think all people who buy something after it is
listed are speculating, ridiculous. All CEOs are responsible to
shareholders for the performance of their common stock. I never wanted
5000% return like you falsely claim I just didn't want to lose 90% of my
investment which appears to have been from a pump and dump setup. The
management of DNT bear responsible for their coins performance. If not them
then who? Also if they didn't then why would you yarn on about if you had
bought the ico you would be x better off. I am an holder of common DNT coin
not a day trader you should have more respect for your investors. If they
wish to raise conerns they should be able to without abuse.
