### ISSUE TITLE
User Scoring and Rewarding System

### ISSUE THREAD

**Issue by Manyeto** [district0x/district-proposals#21]
Name

User Scoring and Rewarding System

Purpose

Users with District0x.io in the User Scoring and Reward System spend more active time on the site. They are encouraged to create more ideas than supporters. We can give a great and convenient tool for everyone.Many communities gather ideas or suggestions using different tools. So you're not using District0x.io itself? We can give everyone a great and useful tool.

Description

Users who are members of District0x.io in the Zone, User Rating and Award System,
He should present his ideas and ignore them. There must be a system of points and rewards. District0x.io is the most profitable one. Because you can use very good ideas and use a good idea better. This system will also be useful for District0x.io. Users in the district should be in District0x.io to be happy to share their ideas with others.By using the District0x.io area, we have access to the ability to make money with these skills; So we can strengthen people to improve their lives and do things they love.

Platform will be. The platform will use the core functionalities of district0x 

Ranking and reputation

Users in the District0x.io one should have a scoring and rewarding system to allow them to spend more time on the site and generate new ideas.

For example ;   

It could be the rank system.

20 positive ideas. 1 star or jr member
40 positive ideas. 2 stars or warrior
80 positive ideas like 3 stars or heroes ..

Rewards can be awarded when each level is skipped or with a brilliant idea that will work for each District0x.io.

For those with good ideas, you can pay for ether addresses.

Features

Subsystem can be created.

Tools for every idea to bootstrap: participation, roles, project management, crowdfunding, etc.

the conclusion

Depending on the network system, you can apply this system differently in each district.With District0x.io, you will get maximum efficiency from the manufacturers in the counties.

To the community and District0x.io

**Comment by uvizhe** [comment]
Hi,
take a look at my [proposal](https://github.com/district0x/district-proposals/issues/11). It seems to be similar and maybe it fits your interests so we can combine our effort :)

**Comment by AngeloAdam** [comment]
please send me a direct message on district slack regarding your proposal. @angelo

**Comment by mckmuze** [comment]
I will be closing this one out. This seems more like a bot or feature request that would serve better as a plugin when D0xInfra is launched. If you want to elaborate on how this would work as a market I can reopen.
