### ISSUE TITLE
Pawn shop

### ISSUE THREAD

**Issue by suurais** [district0x/district-proposals#210]
## **Name**: 
PawnShop

## **Purpose**: 
We all have things that we dont really need. One mans garbage is other mans fortune. Purpose of this district is to make a place where we can sell/trade our unnecessary stuff.

## **Description**: 
Seller puts his item for sale for X amount of DNT, adds description of item, picture etc. Buyers can search through some kind of catalog for items they would like to buy. To buy the item, buyer makes DNT transaction. DNT will be kept by a middleman until the buyer confirms that the item has been received. Basically the idea is like ebay but i doubt that ebay would agree to cooperate with district0x to make available these kind of transactions, so there it is... Ofcourse there would be needed comment section, feedback.

## **Ethereum Address**:
0xf9c899bb7de1ce31f42ced8f5ab24a703daf2b21

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on district0x.chat, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches. Considering this proposal is similar to a couple others, a good thing to do would be to read through them and explain why you would want a competing district and how it would be competing.

**Comment by Bradymck** [comment]
This ETH address appears to be going to Bittrex. Please use a wallet you control.

**Comment by suurais** [comment]
Hello. Please send the DNT to this address
0x08071c350f198332b5dda91993588df4df573372
Thank you!


trešdiena, 2017. gada 6. decembris Bradym <notifications@github.com>
rakstīja:
