### ISSUE TITLE
The advertising market district0x.

### ISSUE THREAD

**Issue by atom980** [district0x/district-proposals#219]
# The advertising market district0x.

Advertising-the motor trade. The deployment of this field will give the success of the entire network. DNR will lift first the moon and then to Mars. The scheme is as follows:
The creation of a platform for advertising sales. The winner will determine the voice of the DNI. The advertiser buys time for an ad in any currency other than DNT. Payment goes to the wallets, voting for advertising. The district with the best attendance (highest rating) – stimulates the demand for costly advertising. 
Two methods of voting:
1. Automatically. The voice automatically for a max offer to pay for advertising.
2. Mechanical. You can vote for it's price=0.

Scheme 1. Automatically. The voice automatically for a max offer to pay for advertising:

Step 1: Advertisers rely on advertising.
Step 2: vote for the advertiser MEW.
Step 3: The Winner-The Advertiser 3. Fee for advertising in MEW. Advertisement on the name of the NAME BAZAAR rating of 50% is the best.
Step 4: Advertiser (3) receives the ads, called Bazaar. The advertiser (2) receives the advertising in the MEME FACTORY. Advertiser (x+1) gets to ETHLANCE.

Scheme 2. Mechanical. You can vote for it's price=0.

Step 1: Advertisers rely on advertising.
Step 2: vote for the advertiser MEW.
Step 3: The Winner-The Advertiser 1. 0 fee for advertising in MEW. Advertisement NAME BAZAAR (rating of 50% is the best).
Step 4: Advertiser (1) receives a NAME BAZAAR. The advertiser (2) gets the publicity for the MEME FACTORY.

# The scheme of advertising.
 [схема рекламы.xlsx](https://github.com/district0x/district-proposals/files/1460944/default.xlsx)

                                                 # Рекламный рынок district0x.
Реклама-двигатель торговли. Развертывание этого поля даст успех всей сети. ДНР поднимет сначала луну, а потом на Марс. Схема выглядит следующим образом:
Создание платформы для продажи рекламы. Победитель определит голос ДНР. Рекламодатель покупает время для объявления в любой валюте, кроме DNT. Оплата идет на кошельки, голосуя за рекламу. Район с лучшей посещаемостью (высший рейтинг) – стимулирует спрос на дорогостоящую рекламу. 
Два метода голосования:
1. Автоматически. Голос автоматически за максимальное предложение оплатить рекламу.
2. Механический. Вы можете проголосовать за его цену=0.

Схема 1. Автоматически. Голос автоматически за максимальное предложение оплатить рекламу:
Шаг 1: Рекламодатели делают ставку за рекламу в районе.
Шаг 2 голосуют за рекламодателя кошельками MEW.
Шаг 3: Победитель-Рекламодатель 3. Плата за размещение рекламы в МИУ. Реклама на NAME BAZAAR (рейтинг 50% является лучшим).
Шаг 4: Рекламодатель (3) получает рекламу в NAME BAZAAR. Рекламодатель (2) получает рекламу в MEME FACTORY. Рекламодатель (x+1) получает рекламу в ETHLANCE.

Схема 2.Механический. Вы можете проголосовать плата за рекламу = 0.Шаг 
1: Рекламодатели делают ставку за рекламу в районе.
Шаг 2: голосуют за рекламодателя кошельками MEW.
Шаг 3: Победитель-Рекламодатель 1.  0 плата за рекламу в MEW. Реклама на NAME BAZAAR рейтинг 50% является лучшим.
Шаг 4: Рекламодатель (1) получает рекламу в NAME BAZAAR. Рекламодатель (2) получает рекламу в MEME FACTORY.
[схема рекламы.xlsx](https://github.com/district0x/district-proposals/files/1460944/default.xlsx)

0xd37398E2e24a12ABCDB9966C199b5cD562C3b305

**Comment by Bradymck** [comment]
Closing this. Will work as a plug in or Auxiliary module.
