### ISSUE TITLE
Poll0x

### ISSUE THREAD

**Issue by io4** [district0x/district-proposals#220]
## **Purpose**: 
Allow to run polls in the blockchain. This district will allow to make polls that run in the blockchain, that can not be tampered, which use a custom ERC20 token for entry.

## **Description**: 
The district would have a poll contract that works in three steps:
* Poll is opened, and a ERC20 contract address is specified.
* A hashed and salted value is given to the contract, and _x_ tokens (ERC20 type, _x_ is determined by the one who started poll) are deposited to limit poll to token holders.
* Poll closes, and users reveal the salt and the election (which is verified). Then the tokens are returned.

To make a poll, some DNT tokens are required as a fee.  
The procedure of hashing and salting is made such that the results can not be predicted, which is useful such that nobody can know what a user votes until the vote can not be modified. First, the voter chooses two values, one is the option that is going to be voted and the other a 32 byte salt, then keccak256(vote||salt) is calculated and sent to contract. When poll ends, both values are sent, which are then checked by the contract to match old value.

The polls will be listed in a website, and can be more open (require a common token such as DNT to enter) or private (require a specific token that is made just for that, or oriented to token holders).

The district could be useful for post-ICO 
## **Ethereum Address**:
0x9FCfE63108f0957aAD1C6F2eD30270e8D35C6491

**Comment by Bradymck** [comment]
Hello there, I'm going to close this for now as this seems more like an app than a community or a marketplace. If you would like to elaborate on the market component I can reopen it.

**Comment by io4** [comment]
@Bradymck thanks for pointing out that!
Added a bit more of elaboration of community part which is mostly around rewards for making/completing polls.
> The community can find and share creative polls, or about popular topics. The interface would allow to upvote the open polls, or even reward with some DNT the creators. As the poll can be verified, someone could reward participants for completing the survey.  

For example a very upvoted a rewarded poll would be "Who is going to be the next US president?" and similar.

**Comment by Bradymck** [comment]
If you can elaborate on how this would work market wise I will reopen but right now this sounds more like a prediction market auxiliary module. Reward for this one still went out though FYI. If you would go into detail we can get this as an auxiliary module. 

My suggestion would be to read on token curated registries and think of a way to make a compelling market that would excite people: https://medium.com/@ilovebagels/token-curated-registries-1-0-61a232f8dac7
