### ISSUE TITLE
DP#23: Chekin - Marketplace for vacational rent check-ins

### ISSUE THREAD

**Issue by carloslagares** [district0x/district-proposals#23]
**## Name**
Chekin

**## Slack Username**
@kalisto

**## Purpose**
Marketplace for people who rent their houses can outsource the check-in process of each rental through an APP that scan the traveler passport, submit the info to the police and store the legal docs required by authorities for the 3 years required.

**## Description**
General Step-by-Step of the functionality of the district
The district works by these 4 easy steps:
1. User #A becomes a citizen of the District
2. User #B, which is already a citizen, uploads a check-in offer
3. User #A submit a request to complete the check-in plus reward
4. User #B agrees and User #A completes the check-in getting the reward plus rating

**## Back-end**
The back-end uses the next functionalities:

- Posting & Listing
   For upload and content delivery in list formats
- Search & Filtering
   Making it easier to browse and find check-ins
- Ranking & Reputation
- For storing the legal docs, Swarm integration. This will enable users to keep a legal copy of the 
   documents for legal purposes.

 
**## The CheKin Token (CHK)**
The CheKin Token will be used throughout the whole district. It will serve as the following 3, and maybe more to come:

- To Pay users who perform the Ckeck-ins in the properties
- Secure legal docs storage

**## Future Goal**
To be the piece of every other distric0x airbnb like project that uses the Chekin mobile APP to complete travelers registrations.

**## Extra credits**
We are a launched and awarded project (by Vodafone) and we are already testing the mobile APP in Barcelona and Seville getting a fantastic feedback. It will be amazing to test the marketplace functionality inside distric0x universe.

**Comment by tfg615** [comment]
Hey @carloslagares this seems like a great concept, but in my opinion lacks some key detail. I like the concept and the extra credits are a great sign, but I think there are many portions of this "Airbnb" concept that need fleshed out. Upvoting for more information and unique properties to the proposal that District0x could provide - thank you for the submission!!

**Comment by carloslagares** [comment]
HI,

Thanks for the feedback! :)

Maybe I have not explained properly, I was talking with Joe on Slack and
made him an intro of this project.

Basically we are not creating an airbnb project/concept, it is a piece that
everyone using airbnb could use. Once a house is confirmed, you need to
legally register the traveler on the authorities (we now that because we
have been running a company doing that in Seville the last three years) and
we know that the process of registering the travelers once they arrive to
the house is a huge pain, for us, and them as that is the very first
experience they will face (waiting to fill some papers for more than 30
minutes).

BEcause of that we thought on creating a tool to help solve this issue, for
airbnb types of projects (or booking, homeaway or many others) and while
doing so we though the adventages of going ever further helping on the
checking process, instead of you, the owner processing one with our tool
(that is already built and being tested and I mentioned) We have though on
letting anyone with the required reputacion and the forces/network effects
of a marketplace outsource that cheking process to anyone in the community.

I hope this helps to clarify the concept,

Anyway, again, thanks for your time and feedback.

best,

Carlos :)

2017-07-12 18:00 GMT+02:00 tfg615 <notifications@github.com>:

**Comment by tfg615** [comment]
Aha! Sorry for my misunderstanding. I get it now, sounds like a great solution. Perhaps I will test it if I travel to Seville sometime soon :) beautiful country!!

**Comment by carloslagares** [comment]
Haha, yeah, Seville is beautiful, ping us whenever you visit the place, we
also got a nice club near the river, "Puerto de Cuba", you would love it :)

2017-07-12 18:19 GMT+02:00 tfg615 <notifications@github.com>:

**Comment by AngeloAdam** [comment]
please send me a direct message on district slack regarding your proposal. @angelo

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
