### ISSUE TITLE
Cryptocial Security - Earn Tokens Towards Your Retirement

### ISSUE THREAD

**Issue by BrendenMurphy** [district0x/district-proposals#237]
The Problem:
Not everyone has access to Social Security. Even in the U.S. where it has helped the pst generation, it's infrastructure is fading. Every nation needs access to a universal Social Security. 

How It Will Work:
Users will receive tokens by achieving "public deeds" such as lending hard drive space for mining, gaining referrals, and advertising. Each individual will have a cap on how much they can withdraw tokens and when. Smart contracts will allow for pension plans and/or dividends to be dispersed when chosen. There will be terms and conditions that require time-lock periods in which users cannot transfer or withdraw tokens. This will keep the integrity of each token over decades of usage. 

## **Ethereum Address**:
0x6052DaA6e4f647C414f88922fec1CFe86EDEd345

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
