### ISSUE TITLE
Happy Hands

### ISSUE THREAD

**Issue by Romoboy** [district0x/district-proposals#245]
## **Name**: 
Happy Hands

## **Purpose**: 
Supporting communities while spreading awareness!

## **Description**: 
Happy Hand's will be a platform that people/sponsors go to interact. Initially there will be a large pool hosted by the district which users use DTN to put in bids within the timeframe. As the district develops there could be an area for sponsors and their goods to be placed on auction.

Specifics: The Large Pool can be on a timer pulling out 100 DNT after each round ends. The rounds will be ran every 4 hours. Sponsors donate goods to the district which are than raffled. There could be different restrictions such as amounts that are needed or capped per pool. 

All coins used will go directly to the District's wallet. At the end of the month (after wallet amount is returned back to starting amount) 80% of the proceeds will be given to 3 charities. The district chooses 10 each month to pick from. Every user will obtain 1 vote for every DNT that was sent to the district that month. 

## **Ethereum Address**:
0x2F81829b9Aa5b6D92305A1FcC5a8A6B841899B93

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to me directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.

**A few questions:**

- I'm having trouble seeing why this would be a market or community in terms of structure and purpose. Can you clarify starting with why? Also please give examples of how it would be used and by who it would be used by. 
- in terms of 'people/sponsors', what are they sponsoring?
- What are the community members putting in bids for and for what timeframe?
- As the district develops, how do you see it moving forward and for what purpose? 
- Who are people sponsoring and what goods are you wanting to be placed on auction?
- What is the The Large Pool purpose and structure? Would it be a smart contract? If so what would the structure of this pool be exactly to ensure confidence among people who would contribute? 
- What is the difference between the large pool and the 'District wallet'. Also who controls this wallet? 
- How will the charities be verified to ensure the funds did indeed go to that charity? 
- In terms of voting, have you looked into other governance structures to prevent anyone coming in and controlling the market? Also what would they be voting on? 

**Some examples of governance structures:** 

 - **Futarchy** - Prediction markets are used to make decisions to align with bylaws and values. For more on this see [DAOs, Democracy, and Governance](http://merkle.com/papers/DAOdemocracyDraft.pdf) by [Ralph Merkle](https://en.wikipedia.org/wiki/Ralph_Merkle). 
 -   **Liquid Democracy** - A simple system that facilitates direct voting or delegate voting that allows one to remove the delegation of their vote at any time. Hence the term, 'Liquid' you can freely add or remove your vote to any delegate or participate yourself. 
 - **Quadratic Voting** - You can buy voted but it gets more expensive as you do, resulting in diminishing returns. Vitalik proposed something along these lines but with a few modifications to the basic concept and can be found [here](https://www.reddit.com/r/ethereum/comments/4rtpmm/on_coinlock_voting_futarchy_and_optimal/). 
 - **Reputation based systems** - A system that incorporates some of the above with additional reputation staking that puts your reputation on the line, could degrade reputation for inactivity or even require a certain level of reputation to participate in certain governance structures.
