### ISSUE TITLE
Guardian0x: A Decentralized Cyber Threat Intelligence Marketplace

### ISSUE THREAD

**Issue by aongxa** [district0x/district-proposals#246]
## **Guardian0x**: 
![53533434](https://user-images.githubusercontent.com/3825708/35719621-240ee442-07e2-11e8-887e-175e273f0b7b.JPG)

## **A Decentralized Cyber Threat Intelligence Marketplace**: 
Decentralizing the Threat Intelligence Marketplace. Making the internet a safer place for end users through the combination of artificial intelligence and human ingenuity.

## **Description**: 
Guardian0x encourages rapid innovation in the lucrative anti-virus and automated cyber threat intelligence space with precise economic incentives that reward timely and accurate threat intelligence concerning the funds recovery, malintent of files, network traffic and URLs collectively referred to as 'Issues' by utilising human (Mercenaries) and machine intelligence (Guardian Bots) through a decentralized marketplace framework.

The proposed marketplace comprises the the three main human actors which are A-Clients, B -Brokers C-Mercenaries and a fourth non-human actor which is D-Guardian Bots.

### A - Clients: Enterprise and end users with suspect 'Issues'. 
Clients typically report 'Issues' to Guardian0x and are matched by quotation to choose from a select range of solutions. Guardian0x allows Clients to choose from a variety of solutions and subscription plans offered by Brokers (B) on the platform. 

Today’s enterprises and individuals rely on an ad-hoc mixture of anti-virus subscriptions, threat intelligence feeds, and assorted dynamic analysis engines to defend against evolving adversarial cyber activity in real time. Typically when choosing a solution, users must weigh the benefits and drawbacks presented by each solution and decide on the least-worst fit for their environment. 

### B - Brokers: Brokers compete to find the most cost - efficient way to deliver solutions to Clients by hiring Mercenaries and commissioning Guardian Bots (developed by Mercenaries) on the Guardian0x district.

Companies that make it easy for Clients to benefit from the Guardian0x market. 
Brokers collect subscription fees and suspect 'Issues' from their clients (End Users) and introduce issues on the market on their clients’ behalf. Brokers participate in the Guardian0x market via Bounties and Offers in the DNT token and extract timely and accurate malintent classifications to aggregate a solution to be provided to clients. It is the Brokers’s responsibility to distill the 'Resolutions' of various Mercenaries into a simple timely solution that they deliver to their clients (A). 

### C  - Mercenaries: Geographically diverse malware experts and reverse engineers who participate in the Guardian0x network to find resolutions to issues/bounties posted on the network by Brokers. Mercenaries also develop and encapsulate solutions into 'Guardian Bots' which are able to be licensed to the Brokers.

Guardian0x provides a legitimate revenue stream for security experts, also referred to as 'Mercenaries'. Mercenaries dissect the latest suspect Issues provided by the Clients though their Brokers and maintain Guardian0x-connected detection engines (“guardian bots”) that automatically determine malintent. Mercenaries commit to 'Resolutions', public statements/solutions that reflect the results of their analysis into the malintent of the 'Issues'. Those that have committed an accurate Resolutions are rewarded (in DNT) or token of choice for their efforts by Brokers (B). A ranking and filtering system will be roposed to rank top experts. These solutions are then encapsulated by the 'Guardian Bots' engines which are then licenced in the network.

### D (Non-Human Actor) - Guardian Bots Prediction Swarm: Future Development of Guardian0x

In the future, Guardian0x functions as a skill-required twist on a prediction market with thousands of micro-engines (“Guardian Bots”) generated by Mercenaries investigating the latest in malware evolution at machine speed - no human in the loop. Mercenaries are also able to licence/sell the bots to the Brokers to be integrated into a compete solution.

Guardian0x provides a truly global alternative: unencumbered reward for honest work to find cyber security solutions and develop novel AI solutions. The district will foster an ecosystem of broad coverage powered by trillions of “micro-engine” Guardian Bots, in fact authored by geographically diverse security experts around the world and licenced to end users through the platform.

## **Ethereum Address**:
0x851ba137C88A7547596E1B6aE40B601775Fbe006

**Comment by PerryEdu** [comment]
This sounds like an interesting idea but it needs to be elaborated with real-world examples for each stage. For the non-technical individuals like myself with limited understanding of cybersecurity, it is a little difficult to conceptualize.
How would this compare or be an improvement on existing products and companies who offer these services?
Best regards

**Comment by myhndl** [comment]
The coherent parts of this proposal are plagiarized from PolySwarm's whitepaper: https://polyswarm.io/polyswarm-whitepaper.pdf

Examples of plagiarism:
1. `...encourages rapid innovation in the lucrative anti-virus and automated cyber threat intelligence space with precise economic incentives that reward timely and accurate threat intelligence concerning...` - lifted directly from PolySwarm's whitepaper

1. `Today’s enterprises and individuals rely on an ad-hoc mixture of anti-virus subscriptions, threat intelligence feeds, and assorted dynamic analysis engines to defend against evolving adversarial cyber activity in real time. Typically when choosing a solution, users must weigh the benefits and drawbacks presented by each solution and decide on the least-worst fit for their environment.` - another direct copy

1. This proposal: `Guardian0x functions as a skill-required twist on a prediction market with thousands of micro-engines (“Guardian Bots”) generated by Mercenaries investigating the latest in malware evolution at machine speed - no human in the loop.`
PolySwarm: `PolySwarm functions as a skill-required twist on a prediction market with thousands of micro-engines (“workers”)
investigating the latest in malware evolution at machine speed - no human in the loop.`

1. **The title is plagiarized.** I mean, c'mon.

Full disclosure: I work at the company behind PolySwarm and I wrote a substantial amount of the PolySwarm whitepaper.

**Comment by Bradymck** [comment]
@myhndl Hey interesting thanks for pointing out. See now, if the TCR ([The District Registry](https://education.district0x.io/district0x-specific-topics/understanding-distict0x/the-district-registry/)) was live you could have nabbed some money for this find! 🤣 

We are going to be migrating all these over to the District Registry after we launch. Getting closer too, our TCR design pattern is about ready now that we are launching the one for [Meme Factory](https://memefactory.io/) and standardizing everything. 

Regardless, closing out. Thanks for the heads up!
