### ISSUE TITLE
Genome0x: A Decentralized Market of Genomic Assets

### ISSUE THREAD

**Issue by aongxa** [district0x/district-proposals#247]
## **Genome0x: A Decentralized Market of Genomic Assets**: 
![capture38830298098232](https://user-images.githubusercontent.com/3825708/35719455-755724aa-07e1-11e8-86be-fdff87801ef5.JPG)

## **Purpose**: 
Genome0x is a decentralized market of genomic assets.

## **Description**: 

The district aims at creating a decentralized genomics infrastructure, that would enable participants to securely:

-Upload genetic information and take control of it.
-Securely store their own genetic information.
-Make profit by selling access to genetic data or part of it.
-Undergo genetic testing in exchange to the right to use genetic information
-Make use of other genetic services.

Participants of the network include;

### Service Vendors —The principal customers of genetic information are companies interested in genetic targeting such as advertising and pharmaceutical companies. 

Obtaining a large amount of genomic information (sequences of genomes togetherwith phenotypic characteristics) is extremely important from the perspective of obtaining the widest possible diversity of genomic information that, in turn, will significantly stimulate the development of the genomic big data market. Genetic Services available in the Genome0x district marketplace between candidates (peer to peer), between service vendors and candidates(business to customer) and between service vendors(business to business) include the following;

-Gene theraphy
-Gene editing
-Genome analysis
-Personalised medicine
-Gene exchange/trade
-Gene sequencing 
-Get individual dietary recommendations or personal training program based on genetic makeup
 
## **Ethereum Address**:
0x851ba137C88A7547596E1B6aE40B601775Fbe006

**Comment by PerryEdu** [comment]
Hello
I think you have a great idea here. To my knowledge such a service does not exist; however, I think that what you are proposing needs more thought and some real-world examples, not just theory. More research would need to be done on the topic to develop categories for clients to search. I personally do not know a great deal about the subject but I do know that it will have a major impact on the world as it develops.
Some areas of study are to slow and even reverse ageing and the growing of human organs.
A database with individuals willing to contribute their DNA and also provide a full physical profile (age, race, ethnic group, eye colour etc.) and a phycological profile (emotional temperament, talents, outlook etc.) would be highly valuable to researchers and companies developing technology in the field).
Participants could all sign agreements that their data and DNA can be used for research and development for commercial use for a fee.  
This is a great idea and one worth pursuing. I would vote for this project - let me know what you think of my proposals.

**Comment by aongxa** [comment]
Hi @Bradymck was this closed in error?
I would have thought all the other proposals are legitimate and original with the exception of the polyswarm idea which was a mistake on my part.
