### ISSUE TITLE
0xchange - a safe, secure, annonymous exchange for fiat and cryptocurrency

### ISSUE THREAD

**Issue by venner78** [district0x/district-proposals#249]
## **Name**:  
0xchange

## **Purpose**: 
To provide users a way to safely, securely and (if desired) anonymously exchange their cryptocurrency for fiat.

## **Description**: 
Users will connect with each other within the district to agree on the terms of the transaction - the fiat/crypto being transacted and the price. Once the transaction is mutually agreed upon, a smart contract will be created ensuring both parties that their funds are secure until the other party has fulfilled their end of the agreement. Only once both parties have completed their end of the agreement will the funds be transferred and the transaction be completed.
The parties will agree on a safe place to meet in person to finalize the transaction, or the funds can be sent electronically to allow the purchase to be completed anonymously if the parties wish. This will provide further safety to both parties by allowing the transaction to be completed without fear of robbery or theft.

## **Ethereum Address**:
0xA7EB419B16d3c0301B8CAB8D96c8D2AB8c171Da8

**Comment by oojacoboo** [comment]
A smart contract can't verify fiat.  So, how do you plan to handle that?

**Comment by Bradymck** [comment]
You may want to collaborate with Shyblugs on his project [Flipper0x](https://github.com/district0x/district-proposals/issues/242), he's part of the project Bitpoint, this is a major focus of their project and they have ideas on how to build this out and are well on their way. You can even take some of the bounties on that link I provided to get involved today. I'll close this one out for now.
