### ISSUE TITLE
Drone0x - Decentralised Drone Instant Aerial Output Marketplace 

### ISSUE THREAD

**Issue by aongxa** [district0x/district-proposals#250]
## **Drone0x - Decentralised Drone Instant Aerial Output Marketplace**: 
![32083029302](https://user-images.githubusercontent.com/3825708/35694895-b33aa100-077a-11e8-8cc1-8ba861f5dcb2.JPG)

## **Purpose**: 
Drone0X aims to be the most comprehensive Decentralised Drone Instant Aerial Output Marketplace on the planet. It is the world's first Instant Aerial Output (IAO) as Service marketplace. Real-time map to show you where drone operators are RIGHT NOW!

### Make money flying your drone. Payments in any DNT, ETH or any crypto.

An drone instant aerial output (IAO) could be categorised into the folowing use cases.

### Phase 01 'IAO' categories
-  IAO command type A **'RECORD!'**- Drone aerial video footage 
- Type B **'3D SCAN!'**- Drone 3D scanned data 
- Type C **'GUARD!'**- Secure real 24hr non-stop aerial surveillance 
- Type D **'AIRLIFT!'** - Drone delivery from point A to B /courier/logistics covering every type of cargo, from online shopping to personal transportation

### Phase 02 (Future Vision of IAO marketplace)
- Full stack Drone transportation network; creating an Uber for automonous air transport (future explansion) to allow users to get from point A to B anywhere on the planet to disrupt and supplant the current state of the transportation and logistics industry on all scales
- Accommodating fully autonomous fleets of drones swarms powered by artificial intelligence to deliver IAOs. Drone owners can participate by 'leasing' their drones on the network to deliver Phase 01 and 02 categories.

### Execution and latency of IAOs
-IAOs are time-based and are executed with smart contract
-Pilots are rewarded for attempting to achieve near-zero latency in the execution of IAOs
-IAO Example Parameters include
TIME range | WEIGHT range | FRAME SIZE | FRAME RATE | CAMERA | LENS | WEATHER | GPS LOCATION

Example Type A;
> IAO-21028 request -1000 DNT 
> Request to Book Pilots Instantly: "Drone pilot required for custom footage in Oxford Street, London."

Example Type B;
> IAO-37827 request -5000 DNT
> Request to Book Pilots Instantly: "Drone pilot required for 3D Scan in of World Heritage Site in Eygpt."

Example Type C;
> IAO-37823 request-9000 DNT
> Request to Book Pilots Instantly: "Drone pilot required for surveillance of high value cargo in Pacific Ocean."

Example Type D;
> IAO-94734 request -95000 DNT
> Request to Book Pilots Instantly: "Drone pilot required for delivery of high value lightweight cargo from New York to San Francisco."

## **Ethereum Address**:
0x851ba137C88A7547596E1B6aE40B601775Fbe006

**Comment by PerryEdu** [comment]
Hello,
I think you have an excellent idea with a great deal of potential. However, I do think it needs more thought on specific applications. I also see an opportunity for income for numerous individuals set up businesses.
Your phase 01 categories need elaboration.
_Real Estate:_ Some ideas that you have not included may be for real estate use. An actual 3D video of a property with video footage all around the property and even neighbours properties to get a better idea of the neighbourhood rather than just relying on real estate brokers pictures (which only show the best shots of the property). This would be ideal for people wanting to buy property in another city or country.
Your idea of a courier service is a good one but there may be legal restrictions.
You have a lot of good ideas that need to be more carefully thought through.
I agree that there is huge potential for drone usage and not just for having a hobby.
This idea is worth pursuing as it certainly has a great deal of potential.

**Comment by PerryEdu** [comment]
Hello again
Another great application would be the tourism industry - huge
Use case: A family is on holiday somewhere and they will be visiting a historic site or a specific location. They want to send a video to friends and family but something different. They book a time and describe what they will be wearing - the drone arrives and videos the location and the people waving (close up and far away). They receive the video in the app and share it with friends and family, social media sites etc. 
This could be a great business for an individual or several individuals in holiday destinations (thousands of them). Bookings could be made on the app (1-hour slots). 
You have a good idea here with substantive potential for success.

**Comment by aongxa** [comment]
Hi @Bradymck was this closed in error?
I would have thought this was a legitimate original proposal.

**Comment by Bradymck** [comment]
Feel free to build out your marketplace and when the [District Registry](https://education.district0x.io/district0x-specific-topics/understanding-distict0x/the-district-registry/) is live you can submit it into the [TCR ](https://education.district0x.io/district0x-specific-topics/meme-factory/what-is-a-tcr/)and see how it goes. 

Though I would be careful about [pulling things from other people's white papers](https://twitter.com/PolySwarm/status/1034941365023436801), you would likely lose your TCR deposit for your actions in general. 

Someone would likely challenge your submission on pure ethical basis, I know I would. After all, even Facebook was denied from the Adchain Registry for ethical reasons, (albeit an unintended consequence). That is the purpose of a TCR, to protect the network from bad actors.

Words of advice, the internet is a permanent place in blockchain, tread lightly and focus on integrity above all else.
