### ISSUE TITLE
Oracle0x - Decentralised Management Consulting and Personal Strategy Marketplace

### ISSUE THREAD

**Issue by aongxa** [district0x/district-proposals#251]
## **Oracle0x**: 
![oracle0x](https://user-images.githubusercontent.com/3825708/36061821-1caa98f0-0e58-11e8-993d-201408b48144.JPG)

## **Purpose**: 
The aim of this district is to create a decentralised management consulting and personal strategy marketplace. Commission specific personal 'strategies' for yourself and your organisation to make better decisions in life and the market. 

Imagine a 'decentralised' Mckinsey. 

Commission research and analysis in specific areas with Oracle0x and receive detailed analysis from experts privately or to be shared with public.  Organisations and individuals running projects can crowdsource the future of the organisation to receive a detailed and specific strategy to inform strategic decisions. For consultants, the two-tiered system of premium fees and competitive bidding allows newcomers in the consulting space  to break into the field and the long tail of the market is utilised in a decentralised context.

Management consulting has grown quickly, with growth rates of the industry exceeding 20% in the 1980s and 1990s. As a business service, consulting remains highly cyclical and linked to overall economic conditions. Increasingly, management consultancy firms are being challenged by disruptive technologies which facilitate work for ex-management consulting freelancers.

As of December 2016, revenues grossed $229.9B with profits of $26.2B. Annual growth from 2011-2016 is expected to increase at a rate of 5.8% year-over-year. The projected growth rate from 2016-2021 is 2.4%, accounting for the potentially disruptive technologies as mentioned before that will affect freelance and independent consultants.

### For Individuals seeking Personal Strategy

- Choose from a range of the best consultants available by domain field (premium fee) or submit an open bid (competitive fee).
- Commission a 'research' with deadline. 
- Formulate a question to be answered.

### TOPIC: LIFESYLE STRATEGY
_eg; What is the best parts of New York to get a 2 bed property with a $2 million budget with my current work location, budget and salary?_

### TOPIC: CAREER STRATEGY
_eg; What are the top game developer companies in London, what are the type of portfolio will get me recruited and what is the most optimal asking salary for interviews?_

### TOPIC: INVESTMENT STRATEGY
_eg; What is the best portfolio weight with optimal risk/reward scenario for me if I make $200000 a year and would like to start investing in cryptocurrencies?_

- Consultants submit application for the research. 
- Review and accept the application. Multiple commissions with the same research question is also possible ed; 3 consultants answering the same question.
- Receive the 'research'.
- Review/rate 'research' (1-5 stars).
- Publish the 'research' (optional) for feedback and review from community.

### For Organisations seeking Organisational + Management Strategy

- Choose from a range of the best consultants available by domain field (premium fee) or submit an open bid (competitive fee).
- Commission a 'research' with deadline. 
- Formulate a question to be answered.

### TOPIC: MARKET STRATEGY
_eg; What is the impact of the blockchain in the next 10 years on our organisation? What are the potential applications in the diamond trading industry?_

### TOPIC: HUMAN RESOURCE STRATEGY
_eg; What are the best regions/ universities / classes to hire talented software developers in Singapore and what is the optimal salary to recruit high quality talent?_

### TOPIC: INVESTMENT STRATEGY
_eg; What is the best portfolio weight with optimal risk/reward scenario for our hedge fund if we make $200 million a year and would like to start a cryptocurrency portfolio?_

- Consultants submit application for the research. 
- Review and accept the application. Multiple commissions with the same research question is also possible ed; 3 consultants answering the same question.
- Receive the 'research'.
- Review/rate 'research' (1-5 stars).
- Publish the 'research' (optional) for feedback and review from community.
_________________________________

### For Individual Consultants

- Get appointed for a 'research'
- Provide quotation if approached by client (premium fee) or bid for work in the marketplace. (competitive fee).
- Request for further information to complete the research.
- Deliver the 'research'.
- Receive review/rating of work. (1-5 stars) to build up individual portfolio.

### For Teams of consultants working together

- Form a team to undertake bigger projects.
- Provide quotation if approached by client (premium fee) or bid for work in the marketplace (competitive fee).
- Get appointed for a 'research' under a team with specific areas of focus 
- Apportion fee to team with contribution weight with smart contract system
- Request for further information from client to complete the research.
- Deliver the 'research'.
- Receive review/rating of team work (1-5 stars)  to build up team portfolio.

### Deliverables to Clients
Full research (securely encrypted) ranging from 2000-50000 words (or more) with additional relevant material in the pack depending on extent of research which may include the following;
- diagrams/charts
- illustration/maps
- computer simulations
- audio/video/VR/AR or 3D data
- relevant research references

### Ranking Mechanism by Domain
Experts are ranked by rating for specific domains (eg; lifestyle, career, investments) with the d0X-INFRA as a backend so the best consultants are automatically matches with the query. With a higher ranking, experts are more likely to be matched with prospective clients, creating an incentive to produce high quality research.

## **Ethereum Address**:
0x851ba137C88A7547596E1B6aE40B601775Fbe006

**Comment by PandaHanda** [comment]
I don't see how this would work. For one there are multiple coins that already try to tackle this issue. 

More importantly the marketplace will never catch on. **At the end of the day the best have clients come to them, not the other way around.**  Its as simple as that.

**Comment by aongxa** [comment]
Thanks for the feedback regarding the flow of matching the clients to consultants, its actually a good point. I've refined the idea so instead so the clients are also able to choose from the best ranked consultants in order to find the best strategists (with premium fees), but they are also able to submit it for open bidding if they want to obtain a wider selection at competitive fee. Users are able to choose from a range of the best consultants available by domain field that is filtered through the ranking mechanism to match with their query.

The idea for this is inspired by https://www.ribbonfarm.com/2017/10/10/the-blockchain-man/ and I think there are many opportunities for freelance consultants to thrive outside the 'organisation'. Regarding multiple coins, there are wider possibilities within the existing space in the market in the next decade.

**Comment by Bradymck** [comment]
@PandaHanda I agree, that other coins attempt to dive into this, though I would argue that this should not be a coin, I don't see a purpose. It should however be a market, especially as @aongxa has reshaped how the market works. 

This is an open system too, they could launch this now in a centralized way and simply use d0xINFRA to hand governance of the market to the users. I can see this working well if it was structured right.
