### ISSUE TITLE
Locker0x - Decentralised Physical Storage Network

### ISSUE THREAD

**Issue by aongxa** [district0x/district-proposals#252]
## **Locker0x - Decentralised Physical Storage Network**: 
![locker0x8930209832](https://user-images.githubusercontent.com/3825708/36062477-40f09040-0e65-11e8-8a30-d8657d545886.JPG)

## **Purpose**: 
Imagine a decentralised Amazon Locker or an Uber for storage.

Locker 0x attempts to reimaginine the world's static and mobile physical storage space, from the scale of an industrial parking lot to the spaces in your bag/luggage/boot!

### Example Unique Use Case - Mobile Lockers
You are travelling in Tokyo with some additional space in your knapsack, become a 'mobile locker' in the Locker0x network by receiving a RFID tagged package from online retailer on behalf of Alice (while she is on a flight from Australia) and store it for 12 hours. 

Item flows from;
### Online retailer warehouse > courier > MOBILE LOCKER (you) > Alice

Instantly receive earnings in DNT or other currencies after Alice collects the item based on your geolocation. 

## **Description**: 
_______________________________________________________________________________________

### Mobile Locker (0.1- 1 sq ft)
Secured spaces distributed around the worlds bags, luggages and car boots.

'Mobile locker' allows items to be securely delivered to mobile spaces in close proximity to people on the move with minimal latency. 

Suitable for; online shopping, close proximity delivery
_______________________________________________________________________________________

### Distributed Locker (1 -100 sq ft)
Secured spaces distributed around the world's backyard and store rooms.
Suitable for; temporary storage, moving houses
_______________________________________________________________________________________

### Mega Locker (100 - 100000 sq ft)
Secured spaces distributed around the world's empty warehouses and industrial buildings.
Suitable for; industrial goods, vehicles, inventory
_______________________________________________________________________________________

## **Ethereum Address**:
0x851ba137C88A7547596E1B6aE40B601775Fbe006

**Comment by Bradymck** [comment]
This is interesting. I have not seen a decentralized version of what UPS is shooting for: https://www.coindesk.com/ups-might-making-locker-accepts-bitcoin/
