### ISSUE TITLE
Vesta District - A Decentralised, User-Driven Social Network

### ISSUE THREAD

**Issue by har00ga** [district0x/district-proposals#261]
# **Vesta District - A Decentralised, User-Driven Social Network**
Inspiration: Vesta is the Roman Goddess of hearth, home and family.

## Purpose

These days, the mere mention of social networks can make ones skin crawl with visions of pervasive data collection, poor development roadmaps and being forced to knees by the whims of the masters. 

The proposal for this district is the first user-driven, user-funded social network that empowers every person to have a say in the ultimate development and outcome of the platform they rely on every day.

## Description

Ideally, the platform would start out rather simple and plain; a basic feed or profile system, for instance. From there, between different forms of democratic election - polling, elected boards and the use of the district0x token in a voting process, users have the ability influence both the ethical ruleset of the community (adhering to district0x's standards, of course) as well as the roadmap of development for additional features and modifications.

Likely there would need to be three essential groups to form at the beginning of this district; developers are of course a key factor, as no project gets off the ground without the builders. It will also need group of people whom have elected control to maintain roadmapping and branding, subject to change as per regular democratic processes. Finally, a team of individuals who can provide support for reports as well as general community concerns. As the ecosystem evolves and changes, undoubtedly more roles and groups will have to be formed.

As there will be a need for people who do a wide variety of tasks from the 'politically' oriented to getting hands-on with the code, there will be something to get into for almost anyone with the passion to help the network. This allows for users to choose to participate directly with the project as much or as little as they'd like, and in whichever way they felt was most useful. 

Eventually, a payment system could be implemented for both developers / bounty hunters, hosting and potentially elected full-time staff, all funded through DNT token votes.

## Pitfalls

* How to ensure the community ethics do not ultimately oppose district0x ethics / applicable laws

* How to ensure people with huge quantities of tokens will not control overall dev[1]

* Namesquatting - as pointed out in replies. 'Tag' method?

1. Becomes simpler as network expands and total quantity / diversity of votes reaches fever pitch

**Wallet:** 0xcb6a81f7ea74de523906e9ea2299da2de8f6bca0

**Comment by jhabdas** [comment]
If implemented it'll usernames can't be squatted as with Twitter or Peepeth. Discourse seems to have a good solution to this problem. Also, attention should be paid for and data protected in such a way privacy policies become a thing of the past.

**Comment by jhabdas** [comment]
If implemented please see to it usernames can't be squatted on as with Twitter or Peepeth. Discourse seems to have a good solution to this problem. Also, attention should be paid for and data protected in such a way privacy policies become a thing of the past.

**Comment by har00ga** [comment]
@jhabdas Agreed on the usernames. I also like Discords naming system, it's similar to how gaming companies like Blizzard have done tags for years. It not only allows people to have the name they actually want, but also enables dynamic changing. This would be a big plus for security.

A process could also be implemented to give someone a fresh number / name at the same time, allowing them to receive a full identity shift. (Should be used sparingly, however.)
