### ISSUE TITLE
shelf - decentralized fan fiction

### ISSUE THREAD

**Issue by Nine27** [district0x/district-proposals#263]
removed

**Comment by Bradymck** [comment]
Do you have a tag preference here?

**Comment by Nine27** [comment]
I think one or both of the following: #fanfiction #publishing

**Comment by Bradymck** [comment]
You have put a lot of work into this, how long have you been working on this?

I have yet to read the full white paper though. I'll comment more when I do.

**Comment by Bradymck** [comment]
Hey, are you moving forward with this on your own instead of waiting for the votes?

Just saw you close it. Keep in mind, after our network is more developed, you can always come back and submit it to the registry. Hope to see you back.

**Comment by Nine27** [comment]
Hey! Yeah, moving forward on my own :)

**Comment by Bradymck** [comment]
Would love to see this develop, can you drop some community links for people to join if they are interested?

**Comment by Bradymck** [comment]
Also, in terms of gaining traction with votes, moving forward independently is a major step towards gaining attention and votes. I'll ping you in Telegram to chat a bit more. 

I have some ideas that may help and some new initiatives I'm working on.

**Comment by Bradymck** [comment]
Ahh I see your ping. Messaging now
