### ISSUE TITLE
Demos0x: allowing anyone to organize a free, fair and safe election on any issue

### ISSUE THREAD

**Issue by Trvllah** [district0x/district-proposals#271]
## **Name**: 
Demos0x

## **Purpose**: 
Demos0x is a voting district that allows for a secure, private and cheap way to hold an election, referendum or other kind of vote using blockchain. Demos0x makes it possible for a public or private organization, individual or government to let a certain group of people decide on a particular issue. 

## **Description**: 
Demos0x is a district that makes voting easy, accessible and safe. Demos0x allows for an individual or organization to organize and hold a vote and decide on the topic, the number of voters, a possible threshold, voter eligibility, voting weight per person, the deadline of the vote, etcetera. In addition, Demos0x makes it possible to execute certain smart contracts as a consequence of the voting result. 
 
The Demos0X district allows for DNT holders to stake (some of) their DNT in a certain vote or election This however doesn't give a holder the right to vote in the election itself but might earn him or her a fee paid by the individual or organization. Alternatively, the individual or organization can buy DNT themselves on the Demos0x district and use these tokens for staking. Demos0x automatically calculates the number of DNT needed for staking based on the number of voters and the specified weight per voter. These DNT will be locked for their holders until after the election or vote. Demos0x exchanges these tokens for tokens that are used on the district for voting. Tokens will be distributed among the participants of the election according to their voting weight. These tokens can only be used for voting on the Demos0x district on the issue set out by the organization or individual. They can’t be traded and DNT holders and other people who didn’t get an invite to vote can’t participate in the election. Participants use the tokens to vote anonymously on the Demos0x district. Since votes are registered on the blockchain everyone can verify the results. A smart contract might be executed automatically once the deadline is over and the results are in. Locked DNT will be unlocked and a possible fee will be paid to the original holders who can use their tokens again as they see fit.
 
Besides staking DNT in a certain vote or election DNT holders can use their tokens for staking in the overall district allowing them to do a proposal for instance on the fee being paid by the individual or organization to DNT holders. 

## **Ethereum Address**:
0x25eb531E2EB0a82A60Cc0112f4455FD6720b80E9

**Comment by Bradymck** [comment]
Unless I'm missing a key structure of the marketplace component, this sounds more like a basic function that will be offered within Aragon. Can you clarify how this marketplace will function as well as how the anonymous voting feature would work? 

If you can clarify how this functions as a marketplace and the differentiation between Aragon governance features I can keep this open. Though as it stands now, it appears more like an Aragon app.

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to me directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mockups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
