### ISSUE TITLE
Delete Me

### ISSUE THREAD

**Issue by Bradymck** [district0x/district-proposals#274]
## **Name**: 
Provide a name of the proposed district. Ideally this would also be listed in the issue title/description.

## **Purpose**: 
Define a purpose of the proposed district. Try to include a one liner with an additional paragraph if needed.

## **Description**: 
Describe how the district should operate in detail. Include relationships between the district and users, tokenholders, and any other parts of the district0x network.

## **Ethereum Address**:
Be sure it is an ethereum address that you control the private key to, tokens sent to an exchange will be lost.

**Comment by AlvinLiangUSC** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened.

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
