### ISSUE TITLE
Representation

### ISSUE THREAD

**Issue by grasponcrypto** [district0x/district-proposals#285]
## **Name**: 
Representation - Liquid Democracy

## **Purpose**: 
For users to become or find a representative.  

## **Description**: 
Post a bio of one's views toward specific districts and the direction they may wish it to lean.  Users who wish to not play such an active role, but still care about long term direction, can participate by allowing their votes to be cast automatically as the same vote as their representative.

"Liquid Democracy is a new form for collective decision making that gives voters full decisional control. Voters can either vote directly on issues, or they can entrust their voting power to delegates (i.e. representatives) who vote on their behalf."

## **Ethereum Address**:
grasponcrypto.stronghodl.eth

**Comment by Bradymck** [comment]
This will be a standard feature within Aragon. I am going to close this for now. However if you have a specific supply and demand market structure you want to outline I can reopen.

**Comment by Bradymck** [comment]
Reward sent
