### ISSUE TITLE
Grow0x

### ISSUE THREAD

**Issue by lukeenterprise** [district0x/district-proposals#287]
## **Name**: grow0x
Grow 0 x is a smart contact for helping the homeless afford wholesale fruits and vegetables.

## **Purpose**: 
Give the homeless 5000 Dnt coins to buy or trade every week for 12 weeks.

## **Description**: 
They can use there coins to buy food or trade for other food. They have the choice to buy food,trade,or can use for any other parts of the district0x network.

## **Ethereum Address**:

0x83D37A0a4F3e55db02fa1CA01E545478c6BF4343

**Comment by Bradymck** [comment]
I have send the DNT reward for this proposal however I do ask you elaborate on how the DNT will be acquired each week and how the marketplace supply and demand will function. This proposal will be closed until then.

**Comment by lukeenterprise** [comment]
Its really just an idea I had to help the homeless. If you have an idea to build around maybe we can build a vr system for homeless. Help them get jobs and teach trades through vr.
