### ISSUE TITLE
MappoDistrict 

### ISSUE THREAD

**Issue by mappoculture** [district0x/district-proposals#289]
[MappoDistrict.pdf](https://github.com/district0x/district-proposals/files/3513151/MappoDistrict.pdf)
[MappoCulture.com](https://mappoculture.com/)
## **Name**: 
MappoDistrict 
## **Purpose**: 
“Mappo District will serve the purpose of providing Smart Self-Sustained living for all Humans and our Planet” 
## **Description**: 
 	Serves as a project to do list, with features allowing all project members to participate in the management of the list. The district will allow members to create task for the to-do list,  and vote on the order in which the task are listed. Members will also use the district to vote on which members are assigned to carry-out the task curated. In order to ensure members are capable of carrying out tasks, The district will also provide a S.K.E Center where members will be able to receive training from one another. The goal of the district is to develop a Global Monetary Energy System via a Distributed Collaborative Platform....Full Spec PDF Available.

## **Ethereum Address**:
0x81c17dDbC19404DB364cC8E29496Ada20eb6da6e

**Comment by Bradymck** [comment]
I assume you meant Planet here? 👇

“Mappo District will serve the purpose of providing Smart Self-Sustained living for all Humans and our Plant”

**Comment by Bradymck** [comment]
Can you elaborate on how you will secure the DNT outlined in the launch plan?

**Comment by mappoculture** [comment]
Hello,
Yes I did. Apologies on grammatical errors a fully edited version shall be up soon.
Thank you,
Nicholas Reyes
Sent from my iPhone

On Aug 15, 2019, at 16:39, Bradym <notifications@github.com<mailto:notifications@github.com>> wrote:


I assume you meant Planet here? 👇

“Mappo District will serve the purpose of providing Smart Self-Sustained living for all Humans and our Plant”

**Comment by mappoculture** [comment]
Hello,
Yes I did, apologies on the grammatical errors a fully edited version shall be up soon. As for the DNT funding, we plan to secure it through our MappoFund and Memberships. I have Attached an outline for MappoCulture.com<http://MappoCulture.com>, which explain the details. Let me know if you have anymore questions.

**Comment by mappoculture** [comment]
> Can you elaborate on how you will secure the DNT outlined in the launch plan?
> I assume you meant Planet here? 👇
> “Mappo District will serve the purpose of providing Smart Self-Sustained living for all Humans and our Plant”

Yes I did, apologies on pervious grammatical errors an edited versions as be upload . As for the DNT funding, we plan to secure it through our MappoFund and Memberships. I have Attached a preliminary outline for MappoCulture.com, which explain the details. Once the site is launched there will be more information available. Let me know if you have anymore questions. 
[MappoCulture.com.pdf](https://github.com/district0x/district-proposals/files/3513176/MappoCulture.com.pdf)

**Comment by mappoculture** [comment]
Mappoculture.com

**Comment by mappoculture** [comment]
https://mappoculture.com/
