### ISSUE TITLE
DP #30: The True Tonic

### ISSUE THREAD

**Issue by thetruetonic** [district0x/district-proposals#30]
**Name:** The True Tonic

**Purpose:** Provide public engagement to achieve our mission of better harmonizing with the rhythms of nature.

**Description:** The True Tonic is a public band owned via shares traded on an ERC-20 smart contract on Ethereum, and (when on the mainnet) governed and paid out as an Aragon Organization.

By structuring our band as a district, we can raise funds for startup and growth expenses, while giving fans and investors a stake in the future of the band. It also allows us to be totally transparent and allows for easy profit sharing on a regular (hopefully monthly) basis.

And FYI the slack username for this proposal is @thetruetonic -- feel free to reach out to me with any questions. Thanks, all!

**Comment by lkngtn** [comment]
Hey @thetruetonic, I love the prospect of bootstrapping and governing public projects. The general case of someone having an idea, proposing it, and having the community rallying around to support it and also take a stake in the project is really compelling. 

I'm wondering what your thought are on the [1Hive Funding Platform proposal](https://github.com/district0x/district-proposals/issues/3), do you think the Audiophile Societies International idea could operate on top of it?

**Comment by thetruetonic** [comment]
Thanks @lkngt and btw congrats on getting into the first round of new districts!!

Would definitely be interested, especially if there is a recurring support capabilities like Patreon. The best thing Patreon could offer us is their exclusive funders-only content area. The best thing I can imagine is an even better, richer community area that all of us funders can interact in and actually run the organization on a daily.

**Comment by AngeloAdam** [comment]
please send me a direct message on district slack regarding your proposal. @angelo

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.Expanded Text
