### ISSUE TITLE
Around the Block

### ISSUE THREAD

**Issue by redmption** [district0x/district-proposals#31]
Name: Around the Block

Purpose: Connect local travelers going to the same relative areas (grocery store/airport/shopping mall) without the need for hiring a "taxi" type service (Uber/Lyft)

Description: The rise of Uber and Lyft has shown there is a great need for transportation within local areas, but what about the costs associated with those services? Paying full time drivers and benefits is expensive and ultimately passed on to the consumer... But what if there were a system where people in your local area could indicate where they needed to travel to, and by connecting them with locals in the area who are already going to that area could eliminate the high costs of contracting a "taxi" type service? Without needing to pay a part/full time driver and only paying a relatively small fee for participating in the ride (small share of gas cost) two or more people can effectively "carpool" to the same location. Smart contacts can be deployed which indicate the destination and the requested fueling amount which then can be approved or denied by any potential travelers. Identification and rating services could also be implemented to help provide safeguards to travelers.

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.Expanded Text
