### ISSUE TITLE
Completely useless. You can't fund with DNT, you can't fund with ETH. Never enough funds because I'm always just a little short of what's needed. Needed 10,000 DNT - put enough ETH for 17,000 DNT and still not able to fund this mess. Always some script error and there is no 'staking' now it's a straight up 10,000 DNT bill PLUS double whatever amount in DNT to do the transaction that never goes through. No wonder people despise crypto - no consistency and always a ripoff.

### ISSUE THREAD

**Issue by ghost** [district0x/district-proposals#312]
Completely useless. You can't fund with DNT, you can't fund with ETH. Never enough funds because I'm always just a little short of what's needed. Needed 10,000 DNT - put enough ETH for 17,000 DNT and still not able to fund this mess. Always some script error and there is no 'staking' now it's a straight up 10,000 DNT bill PLUS double whatever amount in DNT to do the transaction that never goes through. No wonder people despise crypto - no consistency and always a ripoff. Even with $5,000 it sees 0 ETH and not enough gas. I don't know why I wasted my time building a useful district when it was always going to result in nothing. Oh, and here's something nice: Metamask is complete garbage. Just lost $3,000 trying to get my business off the ground and thanks to some skillful scripting, I lost that too. Nice.

_Originally posted by @virtuals-usa in https://github.com/district0x/district-proposals/issues/311#issuecomment-812780237_

**Comment by Bradymck** [comment]
Please join our discord so we can help you with the registry. You can open a support ticket and we can resolve the issue.
