### ISSUE TITLE
Dynamic Network System

### ISSUE THREAD

**Issue by Marcus0x** [district0x/district-proposals#32]
Name: 

Dynamic Network

Purpose: 

 The most beautiful aspect of my decentralized system is to use a dynamic network system. In this system the main center will appear to be missing. Any sub-network will be the main zone when necessary. The purpose here is district0x, which owns a dynamic network of control structures, ideas, materials, and money to be sold. With District0x, customers will be able to get what they want. A dynamic network system will be set up for this. The system to be established will create a dynamic network for customers and sellers by creating a dynamic network. Sale, and transfer will be supported without any problems. The important thing is to provide satisfaction of the parties. In this way, the reliability of District0x will increase. 

To be able to do all that, organizations and investors can create the District0X Dynamic Network zone by investing in the network zone.

Description

With a dynamic network, a decentralized economy will be created. Organizations, buyers and sellers will not be exposed any more and this area can be a good starting point for making money.

The dynamic network system will work like a mechanism. This mechanism works well when the marker is needed for funding, but it is not absolutely necessary for the functionality of the project.

Organizations must secure the environment for Dynamic Networks in advance. The money order must be fully supervised to prevent resource usage in the District0x currency that will control it.

Payment

Which is the best option to determine payment?

There is no restriction on the payments between buyer and seller. Credit cards, secure payment methods for virtual money transfers can be selected.

Responsibility is between buyer and seller. District0x is not responsible for fraud caused by people themselves.

Features

District0x  Dynamic Network,

Dynamic region,

investors,

institutions,

Receivers - sellers

Example

District0x created a Dynamic Network for the purchase and sale of a range of commodities in East America. We made a statement to support this Network. The money for the Dynamic Network provided the support of investors and organizations.

Region District0x can determine who can enter this trade network(North korea, india etc ..). District0x sets up the dynamic territory for the buyers and sellers, buyers and markets of the goods.(İndiana, New york, Florida etc..)

The seller entered the Florida network. Sub region visited the servers.

Example

East America

District0x - FLORİDA

server : >Distict0x - F - server 1 (Car)
                                     server 2 (game)
                                     server 3  (Products)
                                     server 4 (finance)
                                     server 5  (Computer hardware) 
                                     server11 (transfer) etc..

(Example) The buyer entered the car server and bought a car. The buyer who paid the price of the vehicle paid 1 million coins from the virtual transaction. District0X makes small interruptions in purchasing ( %3 - % 10 etc.. )

District0X makes small interruptions in purchasing, selling and transferring.In other words, District0x can achieve the required monetary volume and remove investors' money. You can even make a profit.

**Comment by Marcus0x** [comment]
I'm Sorry. I do not know how to put pictures. I could have done better.

**Comment by Marcus0x** [comment]
Nice,  Interesting subject.  It could have been more detailed.

**Comment by mckmuze** [comment]
I'm going to close this proposal out for now. If you would like to elaborate on this and flesh out the details or include mock ups, it may help people understand the purpose and functions of this market. The description could use more work as well to explain what a 'dynamic network' is in your vision and how it would work functionally.
