### ISSUE TITLE
DP #36: Autoshare | Decentralized autonomous vehicle sharing marketplace

### ISSUE THREAD

**Issue by aureo11** [district0x/district-proposals#36]
# Introduction

Within the very near future (5-10 years), fully autonomous vehicles will quickly go from great ideas to actual reality, very quickly disrupting our current transportation models for the better. The confluence of technologies that will enable this reality is explained in [spectacular fashion](https://www.rethinkx.com/) by futurist Tony Seba. The result will be a dramatic 5-10x decrease in the cost of transportation.

At present, ride-sharing companies such as Uber and Lyft are already salivating at the prospect of a business model that eliminates the most expensive component of their service, the driver. They are expecting to control massive fleets of autonomous vehicles (AV) which we will happily use every time we choose to get around, with the company and their investors reaping the profits.

Yet I see another way. Instead of allowing these corporations to own fleets of AVs designed to maximize their profits, a decentralized AV sharing marketplace would allow anyone to maintain ownership of their own vehicle, while keeping costs down by allowing others to use it the 96% of the time its not needed by the owner. 

# Purpose

The purpose of this district would be to take the underlying functionality provided by the district0x platform and develop an underlying protocol that would allow any AV owner (well except for Tesla, given that they will only allow paid sharing on their own network) to connect to the network. Car owners would be able to set up availability times and customize prices, while users would be able to choose their rides via a variety of factors, including cost, vehicle type, and so forth. I could also see 3rd party services such as car cleaning as part of the ecosystem as well.

# Monetization

I would expect that this project would take a significant amount of capital to launch and popularize, given that it would be competing against serious competition. Token stakers would provide the initial capital in exchange for the rights to the profits coming from the district, which would charge a small 0.5-1% transaction fee for providing the marketplace.

# Feedback desired

I'm sharing this idea as a non-tech person, so I don't have a concrete basis for understanding what is and isn't possible from a coding prospective. Obviously this isn't something that needs to be created tomorrow, given that AVs aren't yet in use, let alone common use. Still, I see this as just the type of real world problem that can be solved via a decentralized crowd-based platform.

I look forward to elaborating upon my initial idea based on questions and feedback.

Reach me on the District0x Slack @aureo11

**Comment by EndymionJkb** [comment]
There are already services like this for private car sharing (where the customer/renter drives, vs. the car owner). Seems it would be even easier with self-driving cars, since it avoids the obvious problem of the person who needs a car physically getting to the car's location, without requiring the driver to come to them (and then get home somehow), or having to take a cab/uber/lyft there. (I'm assuming the owner could tell the car to drive itself to the renter, and then it could drive itself back to the owner when they're done with it.) 

There would be lots of security and insurance concerns, but presumably all these could be overcome somehow. 

Turo.com, GetAround.com, gocarma.com/news/press-releases/city-carshare-carma/

SideCar got shut down, among other attempts:
https://en.wikipedia.org/wiki/Sidecar_(company)

**Comment by aureo11** [comment]
While there are clearly car-sharing (renting) services today, they all take enormous fees. Turo and GetAround charge 30-40% commissions. Part of this expense does cover insurance, but a good portion of it is the companies' profit margin.

Truly automated self-driving cars will reduce the complexity of the two big issues you mentioned; insurance and security. Given that these vehicles will be orders of magnitude safer than human drivers, insurance rates will greatly reduce over time. In addition, since humans can only request destinations, not control how the car gets there, that reduces a lot of security concerns. I'm certain the cars will also contain multiple cameras, so that any damage done by renters can be easily billed to their accounts.

**Comment by AngeloAdam** [comment]
please send me a direct message on district slack regarding your proposal. @angelo

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.Expanded Text
