### ISSUE TITLE
DP #39 District0x World

### ISSUE THREAD

**Issue by Stalker14** [district0x/district-proposals#39]
**Name**

District World

**Purpose**

The greatest trouble for man is time, space and money.  If people are not interested in what they love, it is essential. Of course, not only the poor ones but also the other wealthy do not have time for things they want to do, even if they do not have the opportunity.  We have limited possibilities. The world of the region will take us outside these boundaries. That's why we have the District World. To do this, the project must be developed and marketed
What is needed ,

**Description:**

District0x management, the project for 'District0x World' must pass the test. It establishes a funding system for this. Investors and willing donors will provide the necessary financing. District0x management can generate money on its own economic power and investors by running the money in the decentralized economy. The project, will work well for projects that need financing.

Without permission from any state, Members will freely implement the projects, ideas and financial transactions they wish to make. Actions such as activity or organisation are not inconvenient.

Members are trained to use this project. District0x determines the duration of the training, its purpose, its qualities in the direction of the user's request and in his / her own request. It can create a funding for education.

**needs**

Distict0x World

A network and subregions

Profile

membership

voluntary donors, 

investors

A Functional Mechanism

**Example **

Mike is so bored in his daily life. He wants to play tennis at work, but friends do not want to play games with Mike no matter what the days are. Mike was alone. This is not a problem for Mike. Because Distict is a member of the world, it gives an advantage in real life. Mike enters District0x world membership and enters the nearest sub-region. She introduces herself by phone to play tennis with herself. The District0x World member sees 2 people and Mike. One of the guys wanted $ 10 and the other $ 5. Mike chooses the person who is asking for a more affordable fee. There is no support Mike wants to do on this count. With District0x World, Mike has won new real friendships.

**Example 2**

John is working on a project. There is a problem. There is not enough graphic information about the project. There is no one with graphic information around. John, District World calls someone who wants to help him. It connects to the lower part and reaches a graph named Selena. John accepts the money and has Selena do the graphics work.

**Comment by Marcus0x** [comment]
Nice. Could be more detailed.

**Comment by Manyeto** [comment]
Good writing. Not bad..

**Comment by Stalker14** [comment]
I could write more. I chose to be simple understandable.

**Comment by mckmuze** [comment]
This sounds similar to 1Hive #3 in it's current form. If you would like to elaborate on how this would be different and why it would work better as a separate district I can reopen.
