### ISSUE TITLE
DP #42 Altruistam: A decentralize platform to give effectively.

### ISSUE THREAD

**Issue by christianeg** [district0x/district-proposals#42]
**Name:** 

Altruistam

**Purpose:**

Most of us want to make a difference. We see suffering, injustice, and death, and are moved to do something about them. But working out what that ‘something’ is, let alone doing it, is a difficult problem.

Which cause should you support if you really want to make a difference?  Which charities will use your donation effectively? If you don’t choose well, you risk wasting your time and money. But if you choose wisely, you have a tremendous chance to improve the world. 

Taking advantage of the opportunity we have is challenging. If we don’t think carefully about how to do good, we risk wasting our time and money doing things that don’t actually work.

**Description:**

The purpose of the district is to have a common place to give effectively to achieve the biggest possible impact with your charitable donation. It is also a new approach to teaching people about charitable giving.

During the voting period, participants get introduced to the covering basic concepts of effective giving,  learn about several pre-selected charities, think about and discuss the relative merits of each, and choose which charity will receive the money at stake (which could be pre-donated by the participants or sponsored by an outside party). 

By framing giving as a choice between good options, the district encourages people to be intentional, informed, and impactful in their giving.

https://www.altruistam.com/

Resources: 

http://www.givewell.org/
https://www.effectivealtruism.org/
https://www.thelifeyoucansave.org/Giving-Games

**Comment by GriffGreen** [comment]
Love this! Can't wait to see it in action, definitely check out what we are going with Giveth as well, we are very aligned with this mission! ;-D Sign up for the Giveth Slack at http://slack.giveth.io

**Comment by okmrponcho** [comment]
"learn about several pre-selected charities" 

Who will select the charities?

**Comment by AngeloAdam** [comment]
please send me a direct message on district slack regarding your proposal. @angelo

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
