### ISSUE TITLE
DP #51 👽 Community for Property Owners - Ownernodes

### ISSUE THREAD

**Issue by alphathree** [district0x/district-proposals#51]
**Purpose**
Make building management transparent and efficient for property owners.

**Description** 

When a new "building" is registered, owners of that building can join and be part of the building community. Some of the activities these communities need solved are:

- Meeting scheduling

- Payments for Services 

- Propose and vote on Budgets presented to the building.

- Voting on Admins, Chair Members if needed, Representatives, or any other role. Those roles would acquire certain rights in the platform.

- Claims to Administration, Maintenance.

- Roadmap Proposals of upcoming improvements to the property. 

- Building Proposals (ideas to improve the property, pool, gyms, etc)

- Newsletters, Activity Updates.

-  Rating system for companies engaged with the property. Rating of maintenance people or other services.

- Interface for renters

- Renting Mgmt

slack name : alphathree

**Comment by miguelmarques70** [comment]
Nice proposal.

I've been thinking of something a bit different but all you propose can be used. 

My idea is a decentralise ownership crowdfunding and management for house/building/land, that could bring to live many different projects: permaculture farms, embassies for all sort of proposes, associations and commune housing.

In my case in Porto/Portugal I would use it for an Embassy for Cripto: a living and co-working space to make a bridge local communities and blockchain projects. 

With a good model/platform could be easy replicated for projects with other goals. DP #47: True-Live (co-living lifestyle marketplace) has something to say also.

Maybe other people would like to join and discuss this implementations. For many people decentralise ownership and co-living tools will be very useful in the future.

**Comment by EndymionJkb** [comment]
This is a bit like https://github.com/district0x/district-proposals/issues/37, though mine was more above relieving blight by proposing highest and best uses (and perhaps funding them). We have companies like CrowdRise that do crowdfunding for real estate investment (centralized).

**Comment by oojacoboo** [comment]
The largest issue you're going to find here is that most people do not want to be involved with the most of these items.  It's the reason that properties will hire an HOA to handle these tasks.  It's the reason you elect an HOA board, etc.

This is also the reason that DOAs don't work well.

That said, I think the overall idea is good, but I think it needs to take from the DPOS model.  Where you stake your votes into managers.  These managers then vote and take care of routine business, all of which would be on the blockchain for review.  At any point in time, you can remove your stake with a manager and move it to another.  When a certain nominated or self-interested person gains enough votes, they become a manager.  Or something along these lines.

At the end of the day though, it sounds way too advanced and complex for HOAs and the overall real estate community.  Real estate is a good 5-10 years behind most standard industries when it comes to adopting technology.

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
