### ISSUE TITLE
DP #52 - Venue Platform

### ISSUE THREAD

**Issue by alphathree** [district0x/district-proposals#52]
**Purpose**

Give venues a platform to interact with their guests and members. These venues can range from nightclubs, museums, hotels, even sports stadiums and hospitals.

**Description**

When a new Venue is created, different types of personas would be able to interact. Guests, Managers, Employees. Most Venues will benefit from :

- Billing of tickets, services or products.

- Ranking systems for employees / official members of the venue, tips.

- Event Planning / Execution

- Reward Programs

- Decentralized interactions with guests/patrons/customers. No need to give all your information to part of the Venue/Community. 

- Marketing Channel (coupons, discounts, announcements, etc)

Many of these venues also need internal management and maintenance. That could be another type of district : https://github.com/district0x/district-proposals/issues/51

slack name : alphathree

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
