### ISSUE TITLE
DP #54: MetaSwarm

### ISSUE THREAD

**Issue by joshuam10o** [district0x/district-proposals#54]
## Purpose
Short pitch: A cooperative marketplace for **[Swarm City](https://thisis.swarm.city)** hashtag maintainers and owners. 

Buy and Sell ownership of hashtags, trade partial stakes in popular hashtags, work as an arbitrator on a hashtag (or hire arbitrators for your hashtags), additionally, collectively provide services for hashtag owners like community-run arbitration and management.

## Description

Much of this is intended to describe the existing Swarm City ecosystem to the uninitiated, and only afterwards describe its potential synergies with district0x in a district.

### Hashtags?

Swarm City is a commerce meta-platform, like district0x, that enables service providers and service seekers to transact without involuntary intermediaries, and build reputation in contexts called "hashtags". 

Hashtags are tradeable and ownable assets that require maintainance and activity to retain their value. These hashtags are owned by third parties, who provide arbitration services in the case of a dispute, may maintain and run their own front-end (or "storefront") to the system, and collect flat per-deal fees (in order to give the maintainer the incentive to attract deal volume/real use instead of large deals). These roles may be taken by a single individual, or may be delegated by a hashtag owner to other parties. 

#### Owners
Hashtag owners can be individuals or collectives. There may be a mechanism to optionally tokenize ownership of an existing hashtag, and trade it freely on MetaSwarm (the aforementioned token may be used to claim the fee income of the hashtag), tokenized hashtags will need to have a governance mechanism in place as well, for holders to collaboratively manage the hashtag. Alternatively, hashtags may be traded in a similar way to domains, potentially using much of the same logic as NameBazaar. 

Owners may also manage their hashtag through the MetaSwarm platform by assigning a portion of  the hashtag's fee revenue to various roles, such as (for example):
* Storefront Developers
* Arbitrators
* "Salaried" Service Providers

#### Arbitrators
By default, a hashtag owner needs to manually arbitrate any deals on a hashtag that are put into a state of dispute by a participant of that deal. By wrapping ownership of a hashtag into the MetaSwarm district, these responsibilities can be more easily delegated to other parties. 

Arbitrators can place bids (of percentages of the hashtag revenue) on the role of arbitrating disputes on a hashtag. Good arbitrators can be rated positively by hashtag maintainers, possibly weighted by the transaction quantity those hashtags carry, and build reputation. 

Arbitrators in the district can also build reputation by collaboratively predicting the outcome of a dispute on MetaSwarm enabled hashtags, and hashtag owners can tap into these predictions by delegating arbitration of the hashtag to the district as a whole, instead of giving responsibility to an "individual" arbitrator. 

#### Other Maintainance Roles (Developers, Service Providers)
Hashtag maintainers may want to create maintainance roles other than arbitrators on their hashtag: this would work in exactly the same way as hiring an arbitrator, but need not have a specialized interface other than allowing the hashtag maintainer to communicate with the role provider. There will be a system for hashtag maintainers to create and post arbitrary roles in relation to their hashtag, (which may also be posted to Ethlance) and accept a bid from any applicants. The hashtag maintainer should be able to see the Swarm City reputation of the applicants (if any), their arbitration reputation (if any), and any supporting information they provide (if any).

##### For Owners:
* Tokenization and Governance of Swarm City Hashtags (via Aragon?)
* Marketplace for Hashtag Shares (sorting hashtags by activity volume, activity location, activity distribution)
* Interface for creating and designating roles (sorting applicants by reputation, location, stake)
* Interface for delegating arbitration roles to the MetaSwarm as a whole (each disputed deal is a  prediction market, hashtag owner sets triggers for resolution.)

##### For Role-takers:
*  Interface for applying to hashtags and providing supporting information (potentially also signed proofs-of-identity from other Ethereum addresses).
* Interface to arbitrate deals on hashtags, with the role or without (may need a bridge to Swarm City to communicate with participants of the deal, clarified below).
* Interface to communicate with the hashtag maintainer when you have a non-arbitration role.

##### For Swarm City Participants:
(If a bridge to Swarm City's off-chain infrastructure (over Whisper and IPFS) is deemed unfeasible/out of scope, Swarm City participants on a MetaSwarm-hosted hashtag may be directed to MetaSwarm in order to aide in dispute resolution and interact with the hashtag maintainer(s)).
* Interface to provide supporting information on a deal they are participating in, and communicate with the arbitrator(s).
* Interface to communicate with the hashtag owner/stakeholders, likely with their Swarm City reputation on display.

#
V 👍's appreciated. Contact me on district0x slack, Twitter, reddit @jam10o

**Comment by matrixator** [comment]
This idea is awesome!

**Comment by QueenBeeSC** [comment]
Again, JamO, you have my seal of approval, I love the way you think. This is great!

**Comment by Shentist** [comment]
hashtags could be worth a lot. we should send this funds to the community and devs, to make it possible to create it without funds!

**Comment by joshuam10o** [comment]
They can take Storefront development roles in the MetaSwarm if they want additional income ;) I'm sure any hashtag maintainers would be climbing over each other to have important members of the community,  dev or other hives, taking up roles on their hashtag.

**Comment by mckmuze** [comment]
My main question is would this require development on both district0x's side as well as Arcade City? I'm not fully understanding how this would work. My understanding of Swarm City is limited.

Is Arcade City not allowing a transfer of ownership feature that is built into Arcade City's app directly? This seems like a must if they are doing that and allowing people to profit off of hash tag specific markets.

Can you also elaborate on what the added layer of Aragon and a district UI would do for the Arcade City users? I assume they would need to have three apps for this to work properly. Aragon to govern, disctrict0x market to buy and sell hash tags and arcade city to actually use hash tags. 

If this was a direct partnership, how would you see those three apps being merged and utilized in a way that simplifies the user experience? 

Also, I found a link for more info on the hash tags for reference: https://press.swarm.city/hashtags-revisited-694a7c9ff7a4

I look forward to your responses!

**Comment by joshuam10o** [comment]
Arcade City (which just launched a mobile app) != Swarm City (which has a working Dapp)  just for future reference. Swarm City "brand forked" out of Arcade City, but it looks like the latter has not died either. 

> would this require development on both district0x's side as well as [Swarm City's] side? 

It would primarily be writing up connectors/adaptors/frontends for Swarm City's hashtag registry: Swarm City already has plans for hashtag ownership, and a registry that is in development as we speak. Their codebase is structured in a way that is easy to use elsewhere (however, they are using polymer, so I'm uncertain how easy it will be to merge d0xinfra with Swarm City's components). The main issue, even with the hashtag registry that is in development, is that I haven't seen or heard anything about hashtag transfers or trading, (it isn't mentioned in the link you shared, as an example). That functionality doesn't appear to be part of the flow of the Swarm City Dapp, but looks very much possible with the contracts. 

> Can you also elaborate on what the added layer of Aragon and a district UI would do for the Arcade City users? I assume they would need to have three apps for this to work properly. Aragon to govern, disctrict0x market to buy and sell hash tags and arcade city to actually use hash tags.

The Swarm City ecosystem is anarchic, with (intentionally) no built-in governance mechanisms: these are intended to be "out of channel" using things exactly like this. I just think that it might be a good idea to allow people who wish to have those governance mechanisms the choice of having them (be it in their hashtags owners, a group of hashtag owmers, "hives" of users or service providers,  etc.). It likely wouldn't be something that Swarm City users would notice or see, just like a Uber (for illustration) user doesn't necessarily notice managerial changes in the company unless it affects their bottom line. 

 I'd imagine metaswarm as a backend management interface for hashtag maintainers. Users would only use Swarm City. Traders, managers, and speculators, would likely only use the district UI. Arbitrators would use Aragon. That's all of course if it's unfeasible to merge the three views somehow (ie, embedding SC and Aragon components into the district UI). 

> If this was a direct partnership, how would you see those three apps being merged and utilized in a way that simplifies the user experience?

 I'd love to see d0xinfra being incorporated into Swarm City, the two groups are certainly solving many of the same problems (I will go message @kingflurkel after writing this response), or maybe incorporate SC components in the district UI: things like a list of active deals that allow a hashtag arbitrator  to join in on individual deals' "dealchats" to make better arbitration decisions, or maybe even the entire hashtag be displayed within the district UI. 

Thanks for the insightful questions and interest.

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development on how this coss project collaboration would work or if you are part of the project's team we can reopen. After you have developed your idea more, you will need to reach out to me directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.Expanded Text
