### ISSUE TITLE
DP #55 - Team Management Module - clubspark

### ISSUE THREAD

**Issue by alphathree** [district0x/district-proposals#55]
**Purpose**

Create a module to manage members of a certain team, roles, responsibilities and payment distributions. 

**Description**

This module could be used to instantly set up a financial and logic scheme to manage teams of many sorts in a transparent way (sports teams, academic, cultural, political, or any sort of club) . A team as a district could be used for:

- Voting on new members to join the team
- Payment milestones
- Rewards / Awards / Ratings
- Roles and Responsibilities
- Ratings

Teams can have followers that can join freely, and support the team in several ways. Would be interesting to consider private and public team possibilities and leverage popular tams of people. As well as servicing other kinds of professional teams.

Teams could be an interesting feature for Ethlance, to manage teams of freelancers, as some sort of agency. It could also be interesting to think of teams for the Decentraland project. Where different users would be able to form teams of different sorts in the virtual world as well. 

slack name : alphathree

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
