### ISSUE TITLE
Dp #56 - UI Framework for District0x Experiences

### ISSUE THREAD

**Issue by alphathree** [district0x/district-proposals#56]
**Purpose**

UI Framework that standardizes many UI components to be used in the District0x interfaces. Some customization for certain districts is good, but there should be a baseline, kind of like an Android Guideline, but for Districts. Where UI best practices and specs are distributed and communicated.

**Description**

This library would allow new districts to use a more streamlined and consistent library. Making the platform easier to identify and work with. These would include: 

- UI components (buttons, forms, tags, search bar)
- Invoice and Payment UI Templates (with easy customization)
- Rating/Voting UI components.
- Search Components
- Posting/Listing Layouts/Structures

The idea would be to create a unique visual language (like Material Design in Google), but for district interfaces.

slack name : alphathree

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development and describe how this would be a market or community we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.Expanded Text
