### ISSUE TITLE
DAuction - auction district

### ISSUE THREAD

**Issue by alexandruchis1987** [district0x/district-proposals#60]
## Name

DAuction - auction district

## Purpose

A decentralized auction district where buyers and sellers will not be exposed. Already existing auction systems are centralized in nature and can use their power to provide unfair advantage to some participants. Regular users may feel neglected when not all of the players are playing by the same rules. Our district will ensure the process integrity and data safety.Within DAuction all citizens are equal and have the same rights

The district will allow for owners to list their items for sale and all interested citizens to participate in the auction.

## Simple workflow

The district works by these 4 easy steps:
1. User A which is a citizen prepares the item to be sold.
2. User A announces the district regarding the sale
3. All other interested citizens submit an offer.
4. The district handles the exchange of money and product between the highest bidder and the auctioneer

## Ranking

As citizens execute transactions in DAuction a rating system will be in place so each auctioneer can be reviewed and their rate will be visible for all to see

Slack @alexandruchis

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
