### ISSUE TITLE
DP#68 :WallMindFree-Social relationship Place

### ISSUE THREAD

**Issue by rawafe** [district0x/district-proposals#68]
Purpose
Create an application for social relationships based on the desired level.

Description
General District Use
The district works by following  steps:

One person (P1) joins as a member of the district.
(P1) can give a description of his profile and other members can know about her/him. 

A business (B1), such as  restaurant, cinema, theater, massage center join at the district as a business and offer your services.

(P1) will choose the level of social relationship you want, for examples :

(N1): Relation of friendship,  go to dinner, go to the cinema, to see a match, ..etc.
(N2): Friendship is in the background and the goal of P1 is a sexo relationship and avoid friendship. 

Members can decide the way  to payment to B1. 

Members P1 can feed back the service given by B1.

Backend
The district back-end uses the following features:
• Advertisement and listing
• Search and geolocation filtering
• Facilitate navigation and search for ads
• Classification and Reputation

The back-end will include the integration of the decentralized storage platform for users and business units.
Smart contracts and open source libraries will help control and automate everything from decision making to user voting.

The WallMindFree (WMF)
The WallMindFree Token will be used throughout the district and in each transaction.

The Future of WMF
The next step is to finish the project and let people know how it works. After that, it will be launched in the agreed quotation period.

Slack name: rwallf

**Comment by AngeloAdam** [comment]
please send me a direct message on district0x slack to discuss your proposal @angelo Thanks

**Comment by rawafe** [comment]
Ok Angelo, my slack username is rwallf. I'll do what you say.

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
