### ISSUE TITLE
DP #7 - Web 3.0 Help District

### ISSUE THREAD

**Issue by ddkothar** [district0x/district-proposals#7]
**# Name:**
              Web 3.0 Help District

**# Purpose:**
              Get acquainted with the knowledge of web 3.0. _{Similar to Coursera.}_

**# Description:**
               With so fast moving space, there are loads of enthusiast group yet to enter web 3.0 world. Although there are lots of resources online (Slack, Google, blogs etc.)  but finding and validating them make process cumbersome. What if, on supply and demand perspective --> District is made where there are the service provider (who provide information) and newbies learner to come to engage and learn. E.g. I  want to learn how to start with NMR data analysis, how to setup my storage for filecoin, how to become delegates for cosmos, how to get started with solidity etc. the list is huge with the high volume of basic question (thus I am the consumer). Meanwhile, I can consult for how to set-up MEW, JAXX, how to participate in ICO etc.  Point ---> There is an untapped community where one can teach and one can learn web 3.0. And maybe after learning they can apply for Job market via "Ethlance" and get hired or become a consultant based on there learning and teaching

**Comment by Alexand0x** [comment]
Very cool idea. I wasn't aware of Coursera until now, but it makes sense to extend that kind of service to a niche like web 3.0 with so many pieces to put together.

https://github.com/district0x/district-proposals/issues/49 This is a similar proposal, only with respect to blockchains rather than web 3.0 specifically, but there's a decent amount of overlap. User diop has even laid out his first curriculum in a gist!

**Comment by AngeloAdam** [comment]
@ddkothar please send me a direct message on district0x slack @angelo regarding your district proposal. Thanks.

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.Expanded Text
