### ISSUE TITLE
DP #74 Audio Pool

### ISSUE THREAD

**Issue by chicosonico** [district0x/district-proposals#74]
# My Slack Name: Chicosonico

# Name: Audio Pool

## Purpose:

Currently, the community of music professionals lacks of a good system that can guarantee a fair distribution of the industry royalties and copyrights.
 
AudioPool offers them the possibility of managing their digital assets (songs, samples, remixes, sample packs, etc ), their know-how (tutorials, masterclasses, private classes) and their jobs (producers, singers, musicians, djs, engineers) in a decentralized way, without the middle man and monetize all of them.

## Description:

- The home page should look like a marketplace, organized by a category structure, to allow easy search of content.
- Each professional has a profile where he/she can upload digital assets, learning content, request/offer jobs and any kind of interesting article such an instrument review, device demo, etc.
- People can comment and upvote your content, affecting your popularity and reputation, and increasing your earnings.
- People can make smart contracts and get paid with the invoicing system from district.

## Different scenarios may apply:

For example imagine a Producer who needs to hire a musician to produce a new record, or a DJ who uses someone else stems to remix it, and then the artist upload the entire album in the community. Contracts and invoicing system will keep that process clear and safe.
Artists can upload albums and license them with smart contracts.
Students can learn from tutorials, upvoted and comment, even contact teachers for private lessons.
Students would become a "pro", by getting upvotes, popularity and reputation.
Even listeners would become a curators or music journalists by getting upvotes in their comments.

## Monetization Strategy:

- Similar to steemit.com,  any user in the platform can generate profits by either publishing content and/or curating content from others.
- Popularity and reputation ranking will increase according to number of followers and interactions that you do in the platform.
- Connect with other districts modules getting jobs/assets requests. Imagine a Project Management (DP#73) asking for a soundtrack directly as a public post in AudioPool request category.

### More Pools
The same concept could be work for other artists communities districts:
**TextPool**: for writers, storytellers, screenwriters, poets...
**PaintPool**: Cartoonists, painters, color directors, designers...
**VideoPhotoPool**: Photographers, video artist, light directors...
All of them could be connected with a Project Manager District like https://github.com/district0x/district-proposals/issues/73

**Comment by criscasta** [comment]
Super interesting!! It can be match with my proposal on Project Management! 
There is so much to do for the artist community!!

**Comment by mckmuze** [comment]
Awesome proposal idea. I was thinking of using Ethlance for this purpose but a music specific market makes a lot of sense form a marketing perspective of the app. My proposal could crowdfund a musician on 1hive, then trigger listings on here that are auto paid for and sponsored as they are listed. Upvoted. 

Would love to see this. The project management proposal could also be great for tour management for an artist too. 

My proposal: https://github.com/district0x/district-proposals/issues/64

BTW are you a musician? Would love to hear some tunes!

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.
