### ISSUE TITLE
DP #76: DecPrint

### ISSUE THREAD

**Issue by Bradymck** [district0x/district-proposals#76]
# Name: DecPrint

# Purpose:
To create a decentralized 3d printing market so designers can offer distributed manufacturing services to others. 

# Details: 
A market to accelerate the distributed manufacturing ecosystem that is currently budding. This should start small with individuals and home printers. Larger printers could play a role in this market as it matures.

### Features- 
Distance sorting. This will reduce shipping costs 
Tipping encouragement
Escrow market (Participants can choose to be an escrow for other’s)  
Opt in district pool donations on listings.
Profile donor medal (Possible perks - voting options, revenue shares, tokens, etc)
Multi aspect rating system (Quality, shipping speed, communication, etc)
Tagging system to advertise service offerings (CAD design, material offering tags, 3d scanning, escrow, drop shipping, etc.) 
Design public visibility toggle and licensing info options for 3d designs
People will submit bids and multiple bids can be chosen then pooled into a single price for the requester. 
Possible curation market on IPFS for 3d designs

### Expanded features for non crypto users: 
Coinbase buy widget (Or others similar) (Pay in)
Crypto debit card signup flow (Pay out)
Opt in private key management.

**Comment by imdying** [comment]
>  designers can offer distributed manufacturing services?
not sure I get this statement?!? wouldn't manufacturers offer manufacturing?

**Comment by mckmuze** [comment]
@imdying I guess it could go either way, often times 3D CAD designers will also be printers, I was just spit balling here and it could go many ways, not exclusively so.
