### ISSUE TITLE
DP79 - Reputation Management & Importing

### ISSUE THREAD

**Issue by imdying** [district0x/district-proposals#79]
# Name: RepEx (Reputation Exchange)

### Purpose:

Allow importing of reputation from exiting sources (ebay, amazon etc) to the district0x network. Also allows sharing of reputation between districts. 

This will be an incentive for users who have built up an existing reputation on other platforms to start using district0x districts. 

### Description: 

RepEx allows users to import reputation from exisiting sources through this method:

1. each district0x user is assigned a unique string (e.g. H3DMC2K2)
2. Users add this to each public profile they would like to import the reputation from
3. A service checks the users profile and, if the unique string exists, records the reputation and records it somehow (IPFS?). 
4. The users total reputation is available to the public. Indicators will show the "freshness" of the reputation data and when it was aquired. 

Modules will need to be created for each specific service and updated if the websites change their layout.

Reputation can also be managed for users across districts.

(perhaps this can just be a part of an identity district?)

### Potential issues and solutions:

1. **Users importing the same reputation to multiple accounts.** The RepEx import module could track duplicate reputation imports and flag them as suspicious. 

EDIT: Slack name = rb

**Comment by Alexand0x** [comment]
Great proposal. Seems more appropriate for a module to extend all districts rather than a district in and of itself though.

**Comment by imdying** [comment]
>Seems more appropriate for a module 

Agree. Don't know how modules fit into the scheme of things... Perhaps a similar folder on github for module proposals?

@Alexand0x Is there documentation on how modules might work? All I've seen is what's in the white paper... 

Also maybe there could be a district/marketplace for strictly for modules?

**Comment by Bradymck** [comment]
For now you can add this to the governance section as an issue: https://github.com/district0x/governance

I''m closing this out from the proposals section
