### ISSUE TITLE
DP #81 Franchise Management (Autonomous franchises)

### ISSUE THREAD

**Issue by imdying** [district0x/district-proposals#81]
# Name: Franchiser (FranchisR?  ?!)

### Purpose: 

A district for managing, creating and joining franchises. Existing franchises could migrate to this district to reduce overheads.

Possible solutions:
1. the problem of finding and setting up new franchisees (can create a market of business ideas)
2. transparency of financial transactions of franchisees
3. governance of franchise  (voting on new rules, expenditure etc)
4. Loans for new franchisees (voted on by franchise holders)
5. Distribution and storage of marketing material and training documents
6. Management of territorial licenses and fees required to be paid to franchise.
7. Bulk purchasing and delivery of stock / supplies
8. Access to venture capital 
9. Localisation - Enabling new franchises to legally setup a new franchise according to local laws using a drop down menu. 
10. conflict resolution through aragon/DNT holders.
11. SO MUCH MORE!

### Description: 

A district which allows a user to create an autonomous franchise. 

The user would be able to create contracts allowing users to sell franchise rights to other users. The governance of the franchise could be programatically managed by how much each franchise has at state.

It's late I will write more... I believe the market here is for existing franchises to use the system and avoid accounting costs and legal fees. The market is HUGE.

### Notes - https://en.wikipedia.org/wiki/Franchising

According to the International Franchise Association approximately **44% of all businesses in the United States are franchisee-worked**. 

New Zealand is served by around 423 franchise systems operating 450 brands, giving it the highest proportion of franchises per capita in the world.

By the end of 2012, there were about 2,031 franchise brands operating in Brazil, with approximately 93,000 locations.

China has the most franchises in the world but the scale of their operations is relatively small. Each system in China has an average of 43 outlets, compared to more than 540 in the United States. Together, there are 2600 brands in some 200,000 retail markets.

slack = rb

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.Expanded Text
