### ISSUE TITLE
Public W0rks

### ISSUE THREAD

**Issue by funkyfugu** [district0x/district-proposals#89]
Name: Public W0rks

Purpose: To identify, discuss, and incentivize infrastructure projects of greatest benefit at a local, national, or even global level and to do so with full public transparency.

Description: An online interchange where people can identify, discuss, and vote on the most desired public infrastructure projects on local, national, and even global levels. This could lead to a better informed list of priorities for government. As the district scales, the system could grow to incentivize, with start-up funding, grass-roots groups and private-sector professionals to develop and implement the most desired  infrastructure proposals, all with full public transparency.

**Comment by Alexand0x** [comment]
Interesting idea. I'm curious how proposed infrastructure projects would be translated from proposals voted on by DNT token holders to agenda items for political figures - or is this more of a way of building a solid list of proposals for a local or national ballot (so voters can decide?)

**Comment by Alexand0x** [comment]
@funkyfugu dm me (alexander) on the district0x slack about this proposal when you get the chance

**Comment by Bradymck** [comment]
The ‘Elaborate’ tag has now been added. If you would like to add more detail or development we can reopen. After you have developed your idea more, you will need to reach out to Brady directly on Slack, Telegram, or Reddit to have it reopened. 

A closed proposal will only be reopened if a significant amount of effort has been put into developing the idea. A sure fire way to get your proposal reopened is to make mock ups, wireframes or other content that can better conceptualize your idea. Technical details of what tools or processes will also be considered if they are sound and realistic approaches.

Some of the comments you made above would be good to include to help develop this idea a bit more.
