### ISSUE TITLE
DP90: https://coinvoting.github.io - Coin Voting Contract as a Service for districts

### ISSUE THREAD

**Issue by parag-arora** [district0x/district-proposals#90]
# Name  
[coinvoting.github.io](https://coinvoting.github.io): Coin Voting Contract as a Service

# Purpose
Create a decentralised voting service for districts

# Description
  
### Problem Statement 
Problem with most decentralised organisations is people think decisions are controlled centralised. Reason is they don't have tools good enough to create votes and prove quorum. Every district including district0x network requires continuous participation of users to take decisions and there have been standard methods like carbon voting as well as simple voting based on count of users which is widely used. A new contract and a web deployment needs to be done everytime such a voting has to be happen. Distrivote aims to automate poll creations with a click of a button.  

### Proposal
Create a Service where an organisation owner can come, provide information like title, description, number of choices and choices description. User should be able to select if she wants to create a carbon vote like poll or poll backed by number of users. In case of carbon vote like poll, user will enter contract address and will be provided with a downloadable html which can be hosted over their server or they can opt to redirect user to districtvote hosted page served via IPFS. In case of basic voting, user will not be required to enter contract address but can straight forward create a poll for anything which matters. 
Poll creation service can be charged as a small fee equivalent to the contract upload and web serving fee benefitting user in ease of poll creation. 

Author: parora (Slack)

**Comment by lkngtn** [comment]
I think district, and district0x-wide governance is absolutely critical for the success of the project but not sure if this makes sense as a "district"/marketplace. It seems like this should be something that would fit better in the [Governance Repo](https://github.com/district0x/governance), or in the [Carbonvote repo](https://github.com/district0x/district-voting), or perhaps in Aragon's repos somewhere. 

Gave it a thumbs up anyways, because I again I think governance should be a top priority for District0x.

**Comment by Alexand0x** [comment]
I'll echo Luke's comment, that this is super valuable feedback for governance mechanisms and goes above and beyond what a "district" should be.

**Comment by parag-arora** [comment]
@Alexand0x so this should not be considered as proposal but infrastructure? Would I be able to contribute to that?

**Comment by Bradymck** [comment]
@parag-arora So sorry for the delay in response but yes, you absolutely can contribute to that by moving this over to the governance proposal section: https://github.com/district0x/governance

I'm going to close this out so you can move it over. I look forward to seeing it added as a governance issue and more governance ideas!
