### ISSUE TITLE
DP #98 - 0xBazaar  // BlockBazaar - Open & Safe Classified Ads

### ISSUE THREAD

**Issue by cryptano** [district0x/district-proposals#98]
<img width="1333" alt="screen shot 2017-08-18 at 23 28 23" src="https://user-images.githubusercontent.com/31100007/29478531-921a1036-846d-11e7-8cfd-96a82e66e46c.png">

(TL;DR at the bottom)

**#PURPOSE**

Classified ads like Craigslist and Gumtree have been around since the early days of the Internet. They are used by millions of people on a daily basis to acquire things they need. The actual trade is either done offline or send via mail (online).

The current systems have vulnerabilities in following areas:

1. _IDENTITY_: most platforms do not have safety measures to verify their users (anonymously), and if they do, they are easy to bypass (SMS verification = new number = done) which may cause issues of trust or nervosity when finalising a deal (especially offline).

2. _SAFETY_: current systems are vulnerable to things like offline scams and mugging. Either the money from the Buyer (B) or the product of the Seller (S) can easily be ripped off during an offline meeting.

3. _LIMITED EXCHANGE OPTIONS_: usually (B) and (S) are limited to local cash currency or barter trade. 

**#DESCRIPTION**

0xBazaar tries to solve all these issues by implementing a combination of blockchain technologies within the Distric0x infrastructure, in order to improve safety for Buyers (B) and Sellers (S).

A transaction would look something like this:

1. (S) posts a mobile phone for 2ETH (as _base currency_). (B) finds item and accepts price/contract. In addition to their reputation within the platform, both parties confirm they are real identities by going through the process of Civic or uPort.

2. Both parties agree on a District0x smart contract with following conditions:

I. (S) and (B) stake a predetermined amount of ETH within the contract (each 5ETH for example) under the condition that once the deal is finalised, both parties get their stake back (offline = once returned home // online = once package received).

II. At the same time, (B) adds the price of the product (2ETH) under the condition that once the product has been received, (S) will automatically receive funds.

(This systems allows both parties to have a security layer on each other: if (B) receives the product but refuses to pay, (S) can put the contract on hold and (B) ends up with 7ETH locked up in the contract. If (B) receives the product and is happy, both finalise the contract and (S) get paid and both get their stake back. (S) also has the added security knowing that (B) can actually pay for the item.)

3. (offline) The transfer can be finalised by scanning a QR code which unlocks the smart contract, returning the stake of both parties and sending over 2ETH to (S) for the product. Alternatively, the finalisation of the contract can be done once both (S) and (B) are back home and confirm the contract. 

4. (optional) Buyer and Seller chose on alternative currency if necessary through 0xProject.

5. (optional) All trades are stored on the District0x platform for invoicing if needed for taxation or archiving.  

**TL;DR**: I am not sure if my explanation makes sense to everyone, but I essentially want a trading platform where people can sell their stuff more safely by verifying their real identities and putting a stake in a smart contract which only finalises once both parties have closed a deal successfully. 

**#CHALLENGES**

1. Civic needs to be implemented into the District0x platform.
2. Processes like these still have vulnerabilities but are potentially safer than current systems. 
3. Too complicated in practice, hence automation and ease of use are highly necessary.

I would love to get some feedback on my idea. If you like, I'd appreciate an up-vote :)

**Comment by mckmuze** [comment]
Hello @cryptano I'm going to be closing this one out for now as this seems like more of a feature request for district0x than a marketplace. If you want to elaborate on how this would work as a market or differentiate itself as a district feel free to elaborate and we can reopen. Also, please reach out to me on Slack with a token address for the DNT.
