### ISSUE TITLE
DP #99 Decentralized Exchange (cryptbroker.io)

### ISSUE THREAD

**Issue by Dtrade16** [district0x/district-proposals#99]
Name: cryptbroker.io

Purpose: to exchange digital assets through an autonomous and decentralized platform with superior usability.

Discription: The cryptocurrency space is expanding and has become host to a variety of digital assets, with more being created rapidly. Soon, many coins will be in circulation and a need for a user friendly and trusted financial network will be required. cryptbroker.io can play an important role in the exchange market, allowing traders and investors to exchange digital assets through an autonomous, trusted and highly user focused trading platform.

**Comment by mckmuze** [comment]
Hello there, I'm going to be closing this out. If you would like to elaborate on how this market would work in detail we can reopen.
